// JS MANEJO DATOS ARCHIVO FACTURA-SERVICIOS - GET_FACT.DLL
//10/12/2021 David.M: Creación

function getObjRegFact() {
  return {
    llave: {
      suc: "",
      cl: "",
      nro: "",
    },
    fecha: "",
    cta: {
      prefijo: "",
      nro_cta: "",
    },
    nit: "",
    id_historia: "",
    fecha_ing_estad: "",
    tabla: JSON.parse(
      JSON.stringify(
        Array(140).fill({
          alm: "",
          art: {
            grupo: "",
            art_comp: {
              cod_art: "",
              clase_art: "",
            },
          },
          cod_lote: "",
          lote_medipow: "",
          cant: "",
          vlr: "",
          dias_trata: "",
          vlr_resul: "",
          vlr_interp: "",
          vlr_later: "",
        })
      )
    ),
    valor_des: "",
    tipo_copago: "",
    copago_estim: "",
    vlr_iva: "",
    medicos: {
      med_cir: "",
      med_ayu: "",
      med_ane: "",
      med_ins: "",
      med_otr: "",
    },
    datos_cir: {
      via: "",
      mult: "",
      nro_cir: "",
      cruenta: "",
      grupo_cir: "",
    },
    otros_datos: {
      puerta_estad: "",
      tarif: "",
      costo: "",
      espec_elab: "",
      detalle: "",
      control_cap_estad: "",
      nro_autor_elab: {
        nro1_autor_elab: {
          pref_autor_elab: "",
          comp_autor_elab: "",
        },
        resto_autor: "",
      },
      control_mes: "",
      f_pago: "",
      bloqueo_imp: "",
      nro_form: {
        ind_form: "",
        nro_ped: "",
      },
      cama_rx: "",
      oper_elab: "",
      fecha_elab: "",
      hora_elab: "",
      hora_aten_estad: "",
      oper_correc: "",
      fecha_correc: "",
      hora_correc: "",
    },
    unid_edad_elab: "",
    vlr_edad_elab: "",
    causa_estad: "",
    embar_estad: "",
    personal_elab: "",
    clase_proc_estad: "",
    tipo_proc_estad: "",
    cod_serv_estad: "",
    finalid_estad: "",
    triage_estad: "",
    tip_diag_estad: "",
    repetid_estad: "",
    tabla_diag_estad: JSON.parse(
      JSON.stringify(
        Array(10).fill({
          cod_diag_estad: "",
          descrip_diag_estad: "",
        })
      )
    ),
    hor_obser_estad: "",
    dias_inc_estad: "",
    tipo_discap_elab: "",
    grado_discap_elab: "",
    estad_sal_estad: "",
    fecha_sal_estad: "",
    hora_salid_estad: "",
    diag_muer_estad: "",
    remite: "",
    espec_remi: "",
    unserv: "",
    tipo_dr: "",
    birads: "",
    macro: "",
    ult_examen_estad: "",
    complejidad: "",
    cup_paq_int: "",
    ordserv: {
      pref_ordserv: "",
      cl_ordserv: "",
      nro_ordserv: "",
    },
    fecha_entr_rx: "",
    hora_entr_rx: "",
    recibido_rx: "",
    oper_entr_rx: "",
    cronico: "",
    destino_refact: "",
    refactura: "",
    oper_corr_rips: "",
    fecha_corr_rips: "",
    recibido2_rx: "",
    mot_bloqueo_rx: "",
    datos_4505: {
      sintom_respi: "",
      _1ra_vez: "",
      planific: "",
      fecha_parto_fur: "",
      talla: "",
      peso: "",
      nro_cont_pren: "",
      fluorosis: "",
      calid_muest: "",
      edad_gest: "",
      sintom_piel: "",
      victi_maltrato: "",
      victi_violencia: "",
      enfer_mental: "",
      form_auto: "",
      despac_for_auto: "",
      oper_despac_for: "",
      tens1: "",
      tens2: "",
    },
    pendiente: "",
    nro_pendi: {
      suc_pendi: "",
      cl_pendi: "",
      num_pendi: "",
    },
    fecha_pendi: "",
    hora_pendi: "",
    nro_entrependi: {
      suc_entrependi: "",
      cl_entrependi: "",
      num_entrependi: "",
    },
    fecha_entrependi: "",
    hora_entrependi: "",
    cant_pendi: "",
    tipo_pendi: "",
    fact_auto: "",
    vlr_iva1: "",
    vlr_iva2: "",
    vlr_iva3: "",
    gest_riesg: "",
    gest_gesta: "",
    gest_croni: "",
    consec_barras: "",
    datos_4505_2: {
      empac_for_auto: "",
      total_desc: "",
      total_sindes: "",
      agud_visual_oi: {
        agud_visual_oi_1: "",
        agud_visual_oi_2: "",
      },
      agud_visual_od: {
        agud_visual_od_1: "",
        agud_visual_od_2: "",
      },
      calc_msne_fin: "",
      calc_vale: "",
    },
    hemo_glicosilada: "",
    hemo_glico_fecha: "",
    fecha_microalbuminuria: "",
    microalbuminuria: "",
    creatinina2: "",
    fecha_creatinina: "",
    tipo_pago: "",
    etapa_vacuna: "",
    tipo_vacuna: "",
    nro_dosis: "",
    tipoetapa_vacuna: "",
    var_cop: {
      sanos_cop: "",
      sanos_nocavi_cop: "",
      caries_cavi_cop: "",
      obtura_cop: "",
      ausente_cop: "",
      nro_dient_cop: "",
    },
    punt_escala_abrev: {
      pt_tipica_mg: "",
      pt_tipica_mf: "",
      pt_tipica_ps: "",
      pt_tipica_al: "",
    },
    fecha_limi_auto: "",
    ord_salida: {
      per_salida: "",
      nro_salida: "",
    },
    orig_rips: "",
    upc: "",
    tab_usuar_capit: JSON.parse(
      JSON.stringify(
        Array(10).fill({
          nro_usuar_capit: "",
        })
      )
    ),
    fecha_accid_rips: "",
    empresa_paci_rips: "",
    fecha_presen: "",
    med_tec: "",
    med2_rx: "",
    ciudad: "",
    observ_rips: "",
    motivo_consul_rips: "",
    tabla_abon_salud: JSON.parse(
      JSON.stringify(
        Array(10).fill({
          fecha_abon_salud: "",
          secu_abon_salud: {
            lote_abon_salud: "",
            comp_abon_salud: "",
            item_abon_salud: "",
          },
          vlr_abon_salud: "",
        })
      )
    ),
  };
}

module.exports = { getObjRegFact };
