// Devualve registros para uso en opciones

let regs_dom = {
  TARIF: () => {
    return {
      llave: "",
      ano: "",
      serv: "",
      estrato: "",
      tarifa: "",
      descrip: "",
      ubicacion: "",
      prod: "",
      clase: "",
      medic: "",
      period: "",
      cant_basi: "",
      cant_comp: "",
      cant_sunt: "",
      frec_rec: "",
      frec_bar: "",
      aforo: "",
      puerta: "",
      tasa_int: "",
      tabla: [
        {
          mes: "Ene",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
        {
          mes: "Feb",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
        {
          mes: "Mar",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
        {
          mes: "Abr",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
        {
          mes: "May",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
        {
          mes: "Jun",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
        {
          mes: "Jul",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
        {
          mes: "Ago",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
        {
          mes: "Sep",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
        {
          mes: "Oct",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
        {
          mes: "Nov",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
        {
          mes: "Dic",
          car_fijo: "",
          con_basi: "",
          con_comp: "",
          con_sunt: "",
          subsid: "",
          otro: "",
          neto: "",
          cant_kva: "",
        },
      ],
      contab: {
        interfaz: "",
        c_costo: "",
        cod_fijo: "",
        cod_basi: "",
        cod_comp: "",
        cod_sunt: "",
        cod_subs: "",
        cod_otr: "",
        cod_neto: "",
        cod_inter: "",
      },
      tabla2: [
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
        {
          tn_resi_limp: "",
          tn_resi_barr: "",
          tn_resi_noap: "",
          comp1: "",
          comp2: "",
          comp3: "",
          comp4: "",
          comp5: "",
          comp6: "",
          comp7: "",
          comp8: "",
          comp9: "",
          comp10: "",
        },
      ],
      tn_resi_apro: "",
      tn_resi_rech: "",
      tabla_compon: [
        { sigla_comp: "" },
        { sigla_comp: "" },
        { sigla_comp: "" },
        { sigla_comp: "" },
        { sigla_comp: "" },
        { sigla_comp: "" },
        { sigla_comp: "" },
        { sigla_comp: "" },
        { sigla_comp: "" },
        { sigla_comp: "" },
      ],
      base_vba: "",
    };
  },

  USUAR_SER: () => {
    return {
      nro_cat: "",
      nombre: "",
      direcc: "",
      ruteo: {
        ruta: "",
        mnz_rut: "",
        cas_rut: "",
      },
      estrato: "",
      tabla_serv: [
        {
          item: "001",
          serv: "",
          estr: "",
          tari: "",
          med: "",
          ano: "",
          mes: "",
          valor: "",
          cuotas: "",
          medic: "",
        },
        {
          item: "002",
          serv: "",
          estr: "",
          tari: "",
          med: "",
          ano: "",
          mes: "",
          valor: "",
          cuotas: "",
          medic: "",
        },
        {
          item: "003",
          serv: "",
          estr: "",
          tari: "",
          med: "",
          ano: "",
          mes: "",
          valor: "",
          cuotas: "",
          medic: "",
        },
        {
          item: "004",
          serv: "",
          estr: "",
          tari: "",
          med: "",
          ano: "",
          mes: "",
          valor: "",
          cuotas: "",
          medic: "",
        },
        {
          item: "005",
          serv: "",
          estr: "",
          tari: "",
          med: "",
          ano: "",
          mes: "",
          valor: "",
          cuotas: "",
          medic: "",
        },
        {
          item: "006",
          serv: "",
          estr: "",
          tari: "",
          med: "",
          ano: "",
          mes: "",
          valor: "",
          cuotas: "",
          medic: "",
        },
        {
          item: "007",
          serv: "",
          estr: "",
          tari: "",
          med: "",
          ano: "",
          mes: "",
          valor: "",
          cuotas: "",
          medic: "",
        },
        {
          item: "008",
          serv: "",
          estr: "",
          tari: "",
          med: "",
          ano: "",
          mes: "",
          valor: "",
          cuotas: "",
          medic: "",
        },
        {
          item: "009",
          serv: "",
          estr: "",
          tari: "",
          med: "",
          ano: "",
          mes: "",
          valor: "",
          cuotas: "",
          medic: "",
        },
        {
          item: "010",
          serv: "",
          estr: "",
          tari: "",
          med: "",
          ano: "",
          mes: "",
          valor: "",
          cuotas: "",
          medic: "",
        },
      ],
      observ: "",
      oper: "",
      fecha_act: "",
      doc_id: "",
      retenedor: "",
      zona: "",
      cod_conex: "",
      cod_igac: {
        zona_igac: "",
        sector_igac: "",
        manzana_igac: "",
        predio_igac: "",
        condic_igac: "",
      },
      hog_comun: "",
      tel: "",
      email: "",
      viv_interes: "",
      fuente_alt: "",
    };
  },

  CONFIG_LECT: () => {
    let array = [];
    for (let i = 0; i < 20; i++) {
      array.push({
        codigo: (i + 1).toString().padStart(2, "0"),
        concep: "",
        normal: "",
        increm: "",
        invert: "",
        promed: "",
        consum: "",
      });
    }
    return {
      tabla_lec: array,
    };
  },

  CONTROL: () => {
    return {
      llave: "",
      per_ant: "",
      nro_ant: "",
      nro_fin: "",
      periodo: [
        { ano_per: "", mes_per: "" },
        { ano_per: "", mes_per: "" },
        { ano_per: "", mes_per: "" },
      ],
      mensaje1: "",
      mensaje2: "",
      mensaje3: "",
      fecha_vence: "",
      fecha_vence2: "",
      recargo: "",
      fecha_exp: "",
      int: "",
      int_ref: "",
      fecha_vence3: "",
      periodo_edit: "",
      oper_cre: "",
      fecha_cre: "",
      oper_mod: "",
      fecha_mod: "",
    };
  },

  EMPRESA: () => {
    return {
      nombre: "",
      direcc: "",
      ciudad: "",
      dpto: "",
      tel: "",
      nit: 0,
      dv: "",
      clave1: "",
      ult_fact: 0,
      ult_per: {
        ano: 0,
        mes: 0,
      },
      clave2: "",
      vlr_dup: 0,
      autoret: 0,
      contab_nit: "",
      barras: "",
      cod_ciu: "",
      nuir: "",
      orden: 0,
      formato_abo: "",
      aprox: 0,
      dir_cont: "",
      int: 0,
      int_ref: 0,
      nuap: "",
      dir_impre: "",
      moviles: "",
      tar_iva: 0,
      autorenta: "",
      suricata: 0,
      clave_ctl: "",
    };
  },

  FACT: () => {
    let objeto = {
      llave: "",
      cat: "",
      rut: "",
      est: "",
      direcc: "",
      tabla: {
        serv_tab: [],
        datos_abon: [],
      },
      observ: "",
      oper_cor: "",
      fech_cor: "",
    };

    for (let i = 0; i < 6; i++) {
      objeto.tabla.serv_tab.push({
        datos_tab: [
          {
            conc: "",
            ano: "",
            mes: "",
            cant: "",
            vlr: "",
            cuota: "",
          },
          {
            conc: "",
            ano: "",
            mes: "",
            cant: "",
            vlr: "",
            cuota: "",
          },
          {
            conc: "",
            ano: "",
            mes: "",
            cant: "",
            vlr: "",
            cuota: "",
          },
          {
            conc: "",
            ano: "",
            mes: "",
            cant: "",
            vlr: "",
            cuota: "",
          },
          {
            conc: "",
            ano: "",
            mes: "",
            cant: "",
            vlr: "",
            cuota: "",
          },
        ],
        sub_tot: "",
        sdo_ant: "",
        int_ant: "",
        int_mes: "",
        ajustes: "",
        refinanc_mes: "",
        refinanc_sdo: "",
        nro_cta: "",
        lec_ant_med: "",
        lec_act_med: "",
        lec_prx_med: "",
        basico: "",
        complem: "",
        suntuar: "",
        noved: "",
        tabla_consu: [
          { ult_cons: "" },
          { ult_cons: "" },
          { ult_cons: "" },
          { ult_cons: "" },
          { ult_cons: "" },
          { ult_cons: "" },
        ],
      });
    }

    for (let i = 0; i < 5; i++) {
      objeto.tabla.datos_abon.push({
        fecha_pag: "",
        cod_pag: "",
        sec_pag: "",
        abonos_ser: [
          { abono_ser: "" },
          { abono_ser: "" },
          { abono_ser: "" },
          { abono_ser: "" },
          { abono_ser: "" },
          { abono_ser: "" },
        ],
        tot_abon: "",
      });
    }

    return objeto;
  },

  ABONOS: () => {
    return {
      fecha_gen: {
        ano_gen: "",
        mes_gen: "",
      },
      fact: "",
      fecha: {
        ano: "",
        mes: "",
        dia: "",
      },
      tabla: {
        vlr_abo: "",
        vlr_ser: [{ vlr: "" }, { vlr: "" }, { vlr: "" }, { vlr: "" }, { vlr: "" }, { vlr: "" }],
        recargo: "",
      },
      observ: "",
    };
  },

  REG_PAGO: () => {
    let objeto = {
      ano_gen: "",
      mes_gen: "",
      ano: "",
      mes: "",
      dia: "",
      cod: "",
      secu: "",
      datos_tab: [],
      recargo: "",
      acum_rec: "",
      refer: "",
      oper_cor: "",
      fech_cor: "",
    };

    for (let i = 0; i < 250; i++) {
      objeto.datos_tab.push({
        nro_fac: "",
        vlr_fac: "",
        vlr_ser: [{ vlr: "" }, { vlr: "" }, { vlr: "" }, { vlr: "" }, { vlr: "" }, { vlr: "" }],
      });
    }

    return objeto;
  },

  DEPEN: () => {
    return {
      cod: "",
      descrip: "",
      responsable: "",
    };
  },

  PQR: () => {
    return {
      llave: "",
      fecha: "",
      nro_int: "",
      medio: "",
      tipo_solic: "",
      usu: "",
      nom: "",
      fact: "",
      dir: "",
      tel: "",
      ser: "",
      mot: "",
      dep: "",
      descrip: "",
      concep: "",
      est: "",
      fecha_sol: "",
      tramite: "",
      respuesta: "",
      fecha_not: "",
      fecha_ssp: "",
      notifica: "",
      hora: "",
      version: "",
      tipo_notifica: "",
      oper_cre: "",
      fecha_cre: "",
      oper_mod: "",
      fecha_mod: "",
    };
  },

  SOLIC: () => {
    return {
      llave: "",
      fecha: "",
      usu: "",
      nom: "",
      dir: "",
      tel: "",
      ser: "",
      cod_tar: "",
      vlr_cnx: "",
      vlr_ini: "",
      vlr_mob: "",
      vlr_mat: "",
      vlr_net: "",
      cta: "",
      observ: "",
      fecha_ins: "",
      oper_cre: "",
      fecha_cre: "",
      oper_mod: "",
      fecha_mod: "",
    };
  },

  PQR_SUI: () => {
    return {
      clase: "",
      cod: "",
      descrip: "",
      definicion: "",
    };
  },
};

module.exports = {
  regs_dom,
};
