// JS MANEJO DATOS ARCHIVO HISTORIA CLINICA
//10/02/2021 Javier.l: creación

function getObjRegHC() {
  return {
    novedad: '',
    llave: '',
    fecha: '',
    hora: '',
    serv: '',
    oper_elab: '',
    med: '',
    esquema: '',
    unid_edad: '',
    vlr_edad: '',
    edad_dias: '',
    etnia: '',
    etnia_ind: '',
    niv_estud: '',
    acompa: '',
    id_acompa: '',
    parent_acompa: '',
    fecha_trans: '',
    hora_trans: '',
    embriaguez_trans: '',
    planific: '',
    revaloracion_medi: '',
    fecha_revaloracion: '',
    hora_revaloracion: '',
    oper_revaloracion: '',
    proceden: '',
    motiv: '',
    signos: {
      und_peso: '',
      peso: '',
      talla: '',
      imc_corp: '',
      sup_corp: '',
      temp: '',
      fcard: '',
      fresp: '',
      tens1: '',
      tens2: '',
      tens_media: '',
      oximetria: '',
      pvc: '',
      aper_ocul: '',
      resp_verb: '',
      resp_moto: '',
      vlr_glasg: '',
      per_cef: '',
      peso_ant1: '',
      peso_ant2: '',
      peso_nacer: '',
      talla_nacer: '',
      edad_gest: '',
      aten_ini: '',
      sintom_respi: '',
      imc_estad: '',
      per_abdo: '',
      lateral: '',
      tanner_pubico: '',
      tanner_genit: '',
      alt_uter: '',
      est_nutri: '',
      peso_prev: '',
      tsh_nacer: '',
      creatinina: '',
      per_tora: '',
      per_mune: '',
      sintom_piel: '',
      victi_maltrato: '',
      victi_violencia: '',
      enfer_mental: '',
      enfer_its: '',
      cancer_seno: '',
      cancer_cervis: '',
      per_braq: '',
      hemo_glicosilada: '',
      hemo_glico_fecha: '',
      microalbuminuria: '',
      fecha_microalbuminuria: '',
      riesgo_cardio: '',
      agudeza_visual_1: '',
      agudeza_visual_2: '',
      microalbuminuria2: '',
      creatinina2: '',
      edu_autoexa_seno: '',
      rela_albumi_creatinina: '',
      erc: '',
      fecha_dx_erc: '',
      trata_its: '',
      cual_its: '',
      citologia_previa: '',
      fecha_cito_previa: '',
      resul_cito_previa: '',
      sexo_sin_proteccion: '',
      prueba_vih_sifilis: '',
      resultado_vih_sifilis: '',
      rela_albumi_creatini_2: '',
      contacto_lepra: '',
      fecha_ult_mamo: '',
      tacto_rectal: '',
      nota_tacto_rectal: '',
      curso_psicoprofilactico: '',
      ult_ano_humi_insul_ame: '',
      ult_ano_golp_bofe_fisi: '',
      gest_golp_bofe_fisi: '',
      ult_ano_forzada_sex: '',
      dejar_fumar: '',
      fecha_creatinina: '',
      estadio_erc: '',
      nro_cigarrillos_diario: '',
      ipa: '',
      rela_albumi_creatini_1: ''
    },
    resul_tacto_rectal: '',
    id_maq_elab: '',
    edad_gest_1ra_vez: '',
    razon_ingr_tardi: '',
    ips_reali: '',
    telesalud: '',
    prorroga_inc: '',
    salud_oral_ult_12mes: '',
    salud_oral_ult_6mes: '',
    esq_vacuna_completo: '',
    requiere_findrisk: '',
    requiere_mamografia: '',
    anomalias_congenitas: {
      descrip_anomalia: '',
      seguimien_anomal: '',
      laboratorio_anomal: '',
      fecha_prox_ctl: '',
      fecha_ult_cyd: '',
      fecha_vac_anomal: '',
      fecha_hig_oral_anomal: '',
    },
    tratamiento_sifilis: {
      tabla_tto_sifi: [
        {
          fecha_tto_sifi: '',
          medicamento_sifi: '',
          dosis_sifi: '',
          profe_aplico_sifi: '',
        },
      ],
      tabla_segui_serol: [
        {
          tipo_serol: '',
          fecha_serol: '',
          resul_serol: '',
        },
      ],
      retrata_sifi: {
        nece_retto_sifi: '',
        fecha_retto_sifi: '',
        medicamento_retto: '',
        dosis_retto: '',
        profe_aplico_retto: '',
        cuantos_dias_retto: '',
      },
      dx_contacto: '',
      tto_contacto: '',
      remitio_contacto: '',
    },
    rips: {
      atiende: '',
      triage: '',
      causa: '',
      finalid: '',
      embarazo: '',
      estado_sal: '',
      remitido: '',
      nivel_remit: '',
      observ: '',
      cronico: '',
      primera_vez: '',
      nro_contr: '',
      tipo_diag: '',
      tabla_diagn: [
        {
          cod_diagn: '',
          descrip_diagn: '',
        },
      ],
      discapacidades: {
        fisica: '',
        mental: '',
        cognitiva: '',
        auditiva: '',
        visual: '',
      },
      fecha_1ra_vez: '',
    },
    cierre: {
      clase: '',
      estado: '',
      temporal: '',
      nit_fact: '',
      fact: '',
      hab: '',
      ut: '',
      eps: '',
      servho: '',
      unserv: '',
      admin_unserv: '',
      fecha_unserv: '',
      egreso: '',
      hora_egres: '',
      diag_muer: '',
      tabla_diag_egr: [
        {
          diag_egr: '',
          descrip_egr: '',
        },
      ],
      observ_egres: '',
      oper_ord_salida: '',
      fecha_ord_salida: '',
      hora_salida: '',
      oper_fact: '',
      fecha_fact: '',
      oper_cie: '',
      cl_macro: '',
      cod_macro: '',
      nit_contabilidad: '',
      fecha_grab: '',
      hora_grab: '',
      paciente_cronic: {
        exp_tabaco: '',
        fuma: '',
        humo_lena: '',
        alcohol: '',
        sedentarismo: '',
      },
      fecha_mi: '',
      fecha_endocri: '',
      fecha_cardio: '',
      fecha_oftamol: '',
      fecha_nefro: '',
      fecha_psicol: '',
      fecha_nutri: '',
      fecha_trabsoc: '',
      resul_laborat: '',
      fecha_ini_tto: '',
      fecha_fin_tto: '',
      ctl_mal_3dia_hc: '',
      ctl_mal_7dia_hc: '',
      ctl_mal_14dia_hc: '',
      ctl_leis_45dias: '',
      ctl_leis_6meses: '',
      fecha_ult_cierre: '',
      hora_ult_cierre: '',
      oper_ult_cierre: '',
      cod_ult_cierre: '',
      fecha_ult_reaper: '',
      hora_ult_reaper: '',
      oper_ult_reaper: '',
      cod_ult_reaper: '',
    },
    fecha_prox_cita: '',
    datos_cronic_2: {
      diag_dm: '',
      fecha_diag_dm: '',
      diag_hta: '',
      fecha_diag_hta: '',
      prog_cro: '',
      fecha_prog_cro: '',
      prog_cro_trr: '',
      inas_prog_cro: '',
      ieca: '',
      araii: '',
    },
    citologia_anormal: {
      colposcopia: '',
      fecha_colposcopia: '',
      biopsia: '',
      fecha_biopsia: '',
      fecha_patologia: '',
      diagn_citologia: '',
      valoracion_medi: '',
      fecha_valoracion_medi: '',
      valoracion_gine: '',
      fecha_valoracion_gine: '',
      control_citol: '',
      fecha_control_citol: '',
      fecha_cancer_cuello: '',
    },
    violencia_gen_esc: {
      orientacion_sex: '',
      discapacidad: '',
      vulnerabilidad: '',
      riesgo_psicos: '',
      acciones_reali: '',
      tipo_violencia: '',
      penetracion_anal: '',
      diligencia_viole: '',
      fecha_rem_psiquiatria: '',
      fecha_ate_medicgral: '',
      trabajo_social: '',
      fecha_ate_psicologia: '',
      psicoterapia_individual: '',
      psicoterapia_ind_ejecu: '',
      psicoterapia_familiar: '',
      psicoterapia_fam_ejecu: '',
      fecha_notificacion: '',
      prevencion_its_vsx: '',
      anticoncepcion_emer: '',
      tipo_metodo: '',
      asesoria_consejeria: '',
      consejeria_ive: '',
      ruta_proteccion: '',
      ruta_justicia: '',
      fecha_segui_res459_sem2: '',
      fecha_segui_res459_sem4: '',
      fecha_segui_res459_3mes: '',
      fecha_segui_res459_6mes: '',
      fecha_segui_res459_1ano: '',
      seguimiento_menor: '',
      seguimiento_mujer: '',
      fecha_cierre_res459: '',
      captacion_poblacion: '',
      observaciones_res459: '',
    },
    trastorno_mental: {
      orientacion_sex_ment: '',
      discapacidad_ment: '',
      vulnerabilidad_ment: '',
      tipo_evento_ment: '',
      recaidas_ment: '',
      riesgo_psicos_ment: '',
      acciones_reali_ment: '',
      medicina_gral_ment: '',
      psicologia_ment: '',
      psicote_ind_ment: '',
      psicote_ind_ejec_ment: '',
      psicote_fam_ment: '',
      psicote_fam_ejec_ment: '',
      fecha_remision_psiqui: '',
      fecha_notifica_oblig: '',
      familiar_cuida_ment: '',
      tamizajes_ment: '',
      manejo_tamizaje_ment: '',
      captacion_ment: '',
      consumo_spa_ment: '',
      canaliza_dispos_ment: '',
      acciones_segui_ment: '',
      adherencia_trat_ment: '',
      segui_contra_ment: '',
      fecha_cierre_caso: '',
      evaluacion_mhgap: '',
      pronostico_tera_ment: '',
      observaciones_ment: '',
    },
    multidrogoresis: '',
    cual_multidrogoresis: '',
    examen_visual: {
      agud_visual_oi_1: '',
      agud_visual_oi_2: '',
      agud_visual_od_1: '',
      agud_visual_od_2: '',
      estructuras_oculares_oi: '',
      estructuras_oculares_od: '',
      distancia_agud: '',
    },
    covid19: {
      viaje_covid19: '',
      contacto_covid19: '',
      fiebre_covid19: '',
      tos_covid19: '',
      disnea_covid19: '',
      malestar_covid19: '',
      rinorrea_covid19: '',
      viaje_dentro_covid19: '',
      lugar_dentro_covid19: '',
      tiempo_dentro_covid19: '',
      viaje_fuera_covid19: '',
      lugar_fuera_covid19: '',
      tiempo_fuera_covid19: '',
      odinofagia_covid19: '',
      recomendacion_covid19: '',
      consenti_acomp_covid19: '',
      acompanante_covid19: {
        tipo_id_acomp_covid19: '',
        id_acomp_covid19: '',
        primer_apel_covid19: '',
        segundo_apel_covid19: '',
        primer_nom_covid19: '',
        segundo_nom_covid19: '',
        lugar_id_covid19: '',
      },
      personal_salud_covid19: '',
      paci_confirmado_covid19: {
        diabetes_covid19: '',
        enf_cardiovas_covid19: '',
        falla_renal_covid19: '',
        vih_covid19: '',
        cancer_covid19: '',
        enf_autoinmun_covid19: '',
        hipotiroid_covid19: '',
        cortico_inmuno_covid19: '',
        epoc_asma_covid19: '',
        mal_nutricion_covid19: '',
        fumadores_covid19: '',
      },
      consenti_inform_covid19: '',
    },
    // VARIABLES PARA ACTUALIZACIÓN DATOS ARCHIVO-PACIENTE
    victi_conflicto_paci: '',
  }
}

function getSintomaticoRegHc(regHc = getObjRegHC()) {
  let sintomatico = {}

  sintomatico.sintom_respi = regHc.signos.sintom_respi
  sintomatico.sintom_piel = regHc.signos.sintom_piel
  sintomatico.victi_maltrato = regHc.signos.victi_maltrato
  sintomatico.victi_violencia = regHc.signos.victi_violencia
  sintomatico.enfer_mental = regHc.signos.enfer_mental
  sintomatico.enfer_its = regHc.signos.enfer_its
  sintomatico.trata_its = regHc.signos.trata_its
  sintomatico.cual_its = regHc.signos.cual_its
  sintomatico.cancer_seno = regHc.signos.cancer_seno
  sintomatico.cancer_cervis = regHc.signos.cancer_cervis
  sintomatico.edu_autoexa_seno = regHc.signos.edu_autoexa_seno
  sintomatico.citologia_previa = regHc.signos.citologia_previa
  sintomatico.fecha_cito_previa = regHc.signos.fecha_cito_previa
  sintomatico.resul_cito_previa = regHc.signos.resul_cito_previa
  sintomatico.contacto_lepra = regHc.signos.contacto_lepra
  sintomatico.fecha_ult_mamo = regHc.signos.fecha_ult_mamo

  return sintomatico
}

module.exports = {
  getObjRegHC,
  getSintomaticoRegHc
}
