// JS MANEJO DATOS ARCHIVO EVOLUCION-HISTORIA V2 - GET_EVO.DLL
//03/09/2021 Javier.l: creación

function getObjRegEvoV2() {
  return {
    llave: "",
    fecha: "",
    hora: "",
    tipo: "",
    med: "",
    novedad: "",
    descrip_med: "",
    unserv: "",
    signos: {
      peso: "",
      talla: "",
      imc_corp: "",
      sup_corp: "",
      temp: "",
      fcard: "",
      fresp: "",
      tens1: "",
      tens2: "",
      tens_media: "",
      und_peso: "",
      tanner_pubico: "",
      tanner_genit: "",
      pvc: "",
      glasg: {
        aper_ocul: "",
        resp_verb: "",
        resp_moto: "",
        vlr_glasg: "",
      },
      g_urin: "",
      oximetria: "",
      glucometria: "",
      peso_gramos: "",
      etco: "",
      resul_cito: "",
      muest_cito: "",
      creatinina: "",
      otr_sig: "",
    },
    macro: {
      cl_macro: "",
      cod_macro: "",
    },
    clasif: "",
    via: "",
    datos_cup: {
      tabla_cups: Array(15).fill({ cups: "", descrip_cups: "" }),
      dato_proc: {
        tipo_anes: "",
        tiempo_proc: "",
        tiempo_sala: "",
        sala_cir: "",
        proc_progra: "",
        proc_ambula: "",
        even_adverso: "",
        tipo_cirugia: "",
      },
    },
    creatinina2: "",
    tabla_formu: Array(30).fill({
      tipo: "",
      cod: "",
      descrip_cod: "",
      cant: "",
      indic: {
        indic1: {
          orden_dosis: "",
          cant_dosis: "",
          unid_dosis: "",
          inmed: {
            cada_dosis: "",
            cant_frec: "",
            unid_frec: "",
          },
          via_dosis: "",
          dias_trat: "",
        },
        indic2_1: "",
      },
      var_dosis: {
        cant_dosif: "",
        tipo_dosif: "",
        cant_frec_dosif: "",
        frec_dosif: "",
        via: "",
      },
      cultivo_micro: {
        est_may48_cul: "",
        remitido_cult: "",
        tipo_muest_cult: "",
        antibio1_cult: "",
        antibio2_cult: "",
        antibio3_cult: "",
        antibio4_cult: "",
        antib_otr_cult: "",
        estu1_solic: "",
        estu2_solic: "",
        estu3_solic: "",
      },
      instituto: "",
      tipo_incap: "",
      grado_incap: "",
      prorrog: "",
      nro_ord: "",
      nro_ped: "",
      otros1: {
        observ_interp1: '',
        observ_interp2: '',
      },
      otros2: {
        resul_interp: "",
        vlr_resul: "",
      },
      indic2_2: "",
      cant_formu_fact: "",
      manejo: "",
      espec: "",
      oper_comp: "",
      medico_interp: "",
      datos_fact: {
        llave: {
          suc: "",
          cl: "",
          nro: "",
        },
        fecha_comp: "",
        cta_fact: {
          prefijo: "",
          nro_cta: "",
        },
        hora_elab: "",
      },
      fecha_interp: "",
      aprob_formu: "",
      error_formu: "",
    }),
    estad: {
      tabla_diag: Array(10).fill({ cod_diagn: "", descrip_diagn: "" }),
      rips: {
        embar: "",
        causa: "",
        finalid: "",
        estado_sal: "",
        remitido: "",
        atiende: "",
        unid_edad: "",
        vlr_edad: "",
        diag_muer: "",
      },
    },
    dato_lect: {
      oper_lect: "",
      fecha_lect: "",
    },
    dato_fact: {
      oper_fact: "",
      fecha_fact: "",
    },
    liquidos: {
      liq_adm_oral: "",
      liq_adm_vena: "",
      liq_adm_tran: "",
      liq_adm_orin: "",
      liq_adm_diar: "",
      liq_adm_sond: "",
      liq_adm_otr1: "",
      liq_eli_det: "",
    },
    pupilas: {
      tam_pup_dr: "",
      rea_pup_dr: "",
      tam_pup_iz: "",
      rea_pup_iz: "",
    },
    muscular: {
      msd: "",
      msi: "",
      mii: "",
      mid: "",
    },
    rev_cito: "",
    sintom_respi: "",
    _1ra_vez: "",
    sintom_piel: "",
    metodo_oxi: {
      tipo_met_oxi: "",
      desc_met_oxi: "",
    },
    fcard_fet: "",
    dosis_oxigeno: "",
    per_tora: "",
    per_mune: "",
    tipo_diag: "",
    cronico: "",
    var_crecim: {
      per_cef: "",
      pes_ed_estad: "",
      talla_ed_estad: "",
      peso_tal_estad: "",
      imc_estad: "",
      per_cef_estad: "",
    },
    var_embar: {
      gestaciones: "",
      fecha_regla: "",
      edad_gest_regla: "",
      alt_uter: "",
      peso_prev: "",
      est_nutri: "",
      planific: "",
      otr_planific: "",
      nro_contr: "",
    },
    patologia: {
      pieza_quir: "",
      datos_clinicos: "",
      fecha_muest: "",
      tipo_estud: "",
      histol_estud: "",
      grado_dif_estud: "",
    },
    victi_maltrato: "",
    victi_violencia: "",
    enfer_mental: "",
    enfer_its: "",
    cancer_seno: "",
    cancer_cervis: "",
    lista_chequeo_cir: "",
    hemo_glicosilada: "",
    hemo_glico_fecha: "",
    microalbuminuria: "",
    fecha_microalbuminuria: "",
    riesgo_cardio: "",
    microalbuminuria2: "",
    edu_autoexa_seno: "",
    rela_albumi_creatinina: "",
    erc: "",
    fecha_dx_erc: "",
    trata_its: "",
    cual_its: "",
    citologia_previa: "",
    fecha_cito_previa: "",
    resul_cito_previa: "",
    rela_albumi_creatini_2: "",
    contacto_lepra: "",
    fecha_asesoria_pre_vih: "",
    fecha_asesoria_pos_vih: "",
    fecha_ult_mamo: "",
    conducta: "",
    fecha_creatinina: "",
    estadio_erc: "",
    confusion: "",
    rela_albumi_creatini_1: "",
    estado_formu: "",
    covid19: {
      viaje_covid19: "",
      contacto_covid19: "",
      fiebre_covid19: "",
      tos_covid19: "",
      disnea_covid19: "",
      malestar_covid19: "",
      rinorrea_covid: "",
      viaje_dentro_covid19: "",
      lugar_dentro_covid19: "",
      tiempo_dentro_covid19: "",
      viaje_fuera_covid19: "",
      lugar_fuera_covid19: "",
      tiempo_fuera_covid19: "",
      odinofagia_covid19: "",
      recomendacion_covid19: "",
      consenti_acomp_covid: "",
      acompanante_covid19: {
        tipo_id_acomp_covid19: "",
        id_acomp_covid19: "",
        primer_apel_covid19: "",
        segundo_apel_covid19: "",
        primer_nom_covid19: "",
        segundo_nom_covid19: "",
        lugar_id_covid19: "",
      },
      personal_salud_covid19: "",
      paci_confirmado_covid19: {
        diabetes_covid19: "",
        enf_cardiovas_covid19: "",
        falla_renal_covid19: "",
        vih_covid19: "",
        cancer_covid19: "",
        enf_autoinmun_covid19: "",
        hipotiroid_covid19: "",
        cronico_inmuno_covid19: "",
        epoc_asma_covid19: "",
        mal_nutricion_covid19: "",
        fumadores_covid19: "",
      },
      consenti_inform_covid19: "",
    },
    test_aldrete: {
      conciencia_ald: "",
      color_ald: "",
      brazodr_ald: "",
      brazoiz_ald: "",
      pierndr_ald: "",
      pierniz_ald: "",
      escalof_ald: "",
      exitaci_ald: "",
      venti_ald: "",
      observ_ald: "",
    },
    fecha_susp_oxi: "",
    hora_susp_oxi: "",
    cant_oxi: "",
    peso_new: "",
    id_maq_elab: "",
    reform: {
      llave: {
        id: "",
        folio: "",
        fecha: "",
        hora: "",
        oper_elab: "",
      },
      medico: "",
    },
    cod_bar_dispen: {
      fecha_dispen: "",
      hora_dispen: "",
      pag_dispen: "",
      paci_dispen: "",
    },
    hab: "",
    id_acepta_consen: "",
    especialidad_hc02: "",
    fecha_cita_esp_hc02: "",
    acompa: "",
    prioridad_formu: "",
    per_abdo: "",
    datos_grab: {
      fecha_grab: "",
      hora_grab: "",
    },
    var_examen: {
      inst_exam: "",
      ips_exam: "",
    },
    tabla_cups_ant: Array(5).fill({ cups_ant: "", descrip_cups_ant: "" }),
    datos_tras: {
      oper_tras: "",
      fecha_tras: "",
      llave_paci: {
        id_paci_tras: "",
        folio_suc_tras: "",
        folio_nro_tras: "",
      },
    },
  };
}

module.exports = { getObjRegEvoV2 };
