// JS MANEJO DATOS ARCHIVO DETALLES DE HISTORIA CLINICA
let dllDetalles = {
  2002: "SAVE_WS2002",
  2005: "SAVE_WS2005",
  2070: "SAVE_WS2070",
  2079: "SAVE_WS2079",
  2080: "SAVE_WS2080",
  3010: "SAVE_WS3010",
  4040: "SAVE_WS4040",
  8001: "SAVE_WS8001",
  8002: "SAVE_WS8002",
  8031: "SAVE_WS8031",
  8051: "SAVE_WS8051",
  9005: "SAVE_WS9005",
  9006: "SAVE_WS9006",
  9007: "SAVE_WS9007",
  9008: "SAVE_WS9008",
  9009: "SAVE_WS9009",
  9010: "SAVE_WS9010",
  9011: "SAVE_WS9011",
  9012: "SAVE_WS9012",
  9013: "SAVE_WS9013",
  9014: "SAVE_WS9014",
  9016: "SAVE_WS9016",
  9501: "SAVE_WS9501",
  9520: "SAVE_WS9520",
};

let detallesHc = {
  WS_2002_1: () => {
    return {
      tipo_ws: "",
      patol_cancer: "",
      parent_cancer: "",
      patol_tension: "",
      parent_tension: "",
      patol_tuberculosis: "",
      parent_tuberculosis: "",
      patol_cardiopatias: "",
      parent_cardiopatias: "",
      patol_diabetes: "",
      parent_diabetes: "",
      patol_preeclampsia: "",
      parent_preeclampsia: "",
      patol_eclampsia: "",
      parent_eclampsia: "",
      patol_gemelares: "",
      parent_gemelares: "",
      patol_malformaciones: "",
      parent_malformaciones: "",
      otros: "",
    };
  },
  WS_2002_2: () => {
    return {
      tipo_ws: "",
      patol_asma: "",
      parent_asma: "",
      patol_alergias: "",
      parent_alergias: "",
      patol_tension: "",
      parent_tension: "",
      patol_cardiopulmonar: "",
      parent_cardiopulmonar: "",
      patol_diabetes: "",
      parent_diabetes: "",
      patol_cancer: "",
      parent_cancer: "",
      patol_tuberculosis: "",
      parent_tuberculosis: "",
      patol_sifilis: "",
      parent_sifilis: "",
      patol_epilepsia: "",
      parent_epilepsia: "",
      patol_distrofia: "",
      parent_distrofia: "",
      patol_enfer_mental: "",
      parent_enfer_mental: "",
      patol_anom_congenita: "",
      parent_anom_congenita: "",
      otros: "",
    };
  },
  WS_2002_3: () => {
    return {
      tipo_ws: "",
      embarazo_deseado: "",
      patol_embarazo: "",
      patol_parto: "",
      patol_puerperio: "",
      lugar_nacimiento: "",
      apgar_1_min: "",
      apgar_5_min: "",
      apgar_10_min: "",
      atencion_perinatal: "",
      reanimacion: "",
      grupo_sang_madre: "",
      rh_madre: "",
      serologia_madre: "",
      sano: "",
      hemorragias: "",
      infecciones: "",
      deforma_cong: "",
      hipoglicemia: "",
      apnea: "",
      ictericia: "",
      broncoasp: "",
      neurologia: "",
      memb_hialina: "",
      lactan_materna: "",
      nro_hermanos: "",
      hermanos_muer: "",
      hermanos_vivos: "",
      patologias_familiares: "",
    };
  },
  WS_2002_4: () => {
    return {
      tipo_ws: "",
      asma: "",
      cancer: "",
      diabetes: "",
      tension_arter: "",
      enfer_coronaria: "",
      cerebro_vasc: "",
      neurologicos: "",
      hepatopatias: "",
      obesidad: "",
      infecciones: "",
      alergias: "",
      prob_psicolog: "",
      madre_adolesc: "",
      judiciales: "",
      otros: "",
    };
  },
  WS_2005: () => {
    return {
      ant_canc_fam: "",
      tabla_organo: [],
    };
  },

  WS_2070_1: () => {
    return {
      tipo_ws: "",
      patol_tabaquismo: "",
      patol_alcoholismo: "",
      patol_drog_psicoact: "",
      vacuna_teta: {
        patol_vacuna_teta: "",
        fecha_vacuna_teta: {
          ano_vacuna_teta: "",
          mes_vacuna_teta: "",
        },
      },
      vacuna_hepat: {
        patol_vacuna_hepat: "",
        fecha_vacuna_hepat: {
          ano_vacuna_hepat: "",
          mes_vacuna_hepat: "",
        },
      },
      vacuna_rube: {
        patol_vacuna_rube: "",
        fecha_vacuna_rube: {
          ano_vacuna_rube: "",
          mes_vacuna_rube: "",
        },
      },
      patol_cuagulopatia: "",
      patol_transfusionales: "",
    };
  },

  WS_2079: () => {
    return {
      emb_otros_metodos: "",
      cual_emb_metodo: "",

      diu: {
        diu_con: "",
        diu_usant: "",
        diu_usact: "",
        diu_indic: "",
      },

      oral: {
        oral_con: "",
        oral_usant: "",
        oral_usact: "",
        oral_indic: "",
      },

      barr: {
        barr_con: "",
        barr_usant: "",
        barr_usact: "",
        barr_indic: "",
      },

      diu_barr: {
        diu_barr_con: "",
        diu_barr_usant: "",
        diu_barr_usact: "",
        diu_barr_indic: "",
      },

      impl_sd: {
        impl_sd_con: "",
        impl_sd_usant: "",
        impl_sd_usact: "",
        impl_sd_indic: "",
      },

      sd_barr: {
        sd_barr_con: "",
        sd_barr_usant: "",
        sd_barr_usact: "",
        sd_barr_indic: "",
      },

      oral_barr: {
        oral_barr_con: "",
        oral_barr_usant: "",
        oral_barr_usact: "",
        oral_barr_indic: "",
      },

      inyec_men: {
        inyec_men_con: "",
        inyec_men_usant: "",
        inyec_men_usact: "",
        inyec_men_indic: "",
      },

      men_barr: {
        men_barr_con: "",
        men_barr_usant: "",
        men_barr_usact: "",
        men_barr_indic: "",
      },

      inyec_tri: {
        inyec_tri_con: "",
        inyec_tri_usant: "",
        inyec_tri_usact: "",
        inyec_tri_indic: "",
      },

      tri_barr: {
        tri_barr_con: "",
        tri_barr_usant: "",
        tri_barr_usact: "",
        tri_barr_indic: "",
      },

      emerg: {
        emerg_con: "",
        emerg_usant: "",
        emerg_usact: "",
        emerg_indic: "",
      },

      emerg_barr: {
        emerg_barr_con: "",
        emerg_barr_usant: "",
        emerg_barr_usact: "",
        emerg_barr_indic: "",
      },

      ester: {
        ester_con: "",
        ester_usant: "",
        ester_usact: "",
        ester_indic: "",
      },

      ester_barr: {
        ester_barr_con: "",
        ester_barr_usant: "",
        ester_barr_usact: "",
        ester_barr_indic: "",
      },

      coi_int: {
        coi_int_con: "",
        coi_int_usant: "",
        coi_int_usact: "",
        coi_int_indic: "",
      },

      met_rit: {
        met_rit_con: "",
        met_rit_usant: "",
        met_rit_usact: "",
        met_rit_indic: "",
      },

      no_uso_antic: "",
    };
  },

  WS_2080: () => {
    return {
      edad1_pad_esq_w: "",
      edad2_pad_esq_w: "",

      edad1_mad_esq_w: "",
      edad2_mad_esq_w: "",

      sexo_her1_esq_w: "",
      edad1_her1_esq_w: "",
      edad2_her1_esq_w: "",

      sexo_her2_esq_w: "",
      edad1_her2_esq_w: "",
      edad2_her2_esq_w: "",

      sexo_her3_esq_w: "",
      edad1_her3_esq_w: "",
      edad2_her3_esq_w: "",

      sexo_her4_esq_w: "",
      edad1_her4_esq_w: "",
      edad2_her4_esq_w: "",

      sexo_her5_esq_w: "",
      edad1_her5_esq_w: "",
      edad2_her5_esq_w: "",

      sexo_her6_esq_w: "",
      edad1_her6_esq_w: "",
      edad2_her6_esq_w: "",
    };
  },

  WS_3010_1: () => {
    return {
      tipo_ws: "",
      patol_ardor_ojos: "",
      patol_prurito: "",
      patol_cansancio_ocul: "",
      patol_vision_borrosa: "",
      patol_tamizaje_norm: "",
      patol_lagrimeo: "",
      patol_ojo_rojo: "",
      patol_disfonia: "",
      patol_epitaxis: "",
      patol_hipoacusia: "",
      patol_obstrucc_nasal: "",
      patol_rinorrea: "",
      patol_tinitus: "",
    };
  },

  WS_4040: () => {
    return {
      gineco_esq_w: {
        hemoglob_esq_w: "",
        toma_calcio_esq_w: "",
        toma_hierro_esq_w: "",
        toma_acidof_esq_w: "",
        gine_muertos_esq_w: 0,
        emb_alto_riesg_esq_w: "",
        gine_plane_esq_w: "",
        gine_acept_esq_w: "",
        gine_molas_esq_w: 0,
        gine_obito_esq_w: 0,
        gine_gemel_esq_w: 0,
        gine_vivos_esq_w: 0,
        gine_25_esq_w: 0,
        gine_40_esq_w: 0,
        menarquia_esq_w: 0,
        ciclos_esq_w: "",
        ciclo_irreg_esq_w: "",
        gestaciones_esq_w: 0,
        partos_esq_w: 0,
        abortos_esq_w: 0,
        cesareas_esq_w: 0,
        ectopicos_esq_w: 0,
        fecha_regla_esq_w: "",
        ult_parto_esq_w: "",
        fecha_citol_esq_w: "",
        result_citol_esq_w: "",
        citol_anormal_esq_w: "",
        partos_termino_esq_w: 0,
        partos_prematuro_esq_w: 0,
        fecha_primer_embar_esq_w: "",
        dismenorrea_esq_w: "",
        infec_pelvic_esq_w: "",
        endometros_esq_w: "",
        especuloscop_esq_w: "",
        especul_anormal_esq_w: "",
        ultrason_utero_esq_w: "",
        ultrason_ovario_esq_w: "",
        ultrason_trompa_esq_w: "",
        ultrason_otros_esq_w: "",
        cirugias_gineco_esq_w: "",
        prueba_embarazo_esq_w: "",
        fecha_pru_emb_esq_w: "",
        frotis_flujo_esq_w: "",
        resultado_frotis_esq_w: "",
        fecha_frotis_esq_w: "",
        ult_regla_esq_w: "",
      },

      obstetric_esq_w: {
        edad_gest_regla_esq_w: 0,
        edad_gest_ultra_esq_w: 0,
        fecha_parto_fur_esq_w: "",
        fecha_parto_son_esq_w: "",
        fecha_parto_fur_cale_esq_w: "",
        fecha_parto_son_cale_esq_w: "",
        presentac_esq_w: "",
        situacion_esq_w: "",
        dorso_obs_esq_w: "",
        liq_amniot_vol_esq_w: "",
        polihidram_esq_w: "",
        oligoamnio_esq_w: "",
        implantacion_esq_w: "",
        dist_cervix_esq_w: "",
        frec_card_fetal_esq_w: "",
        umbil_ir_esq_w: "",
        umbil_ip_esq_w: "",
        umbil_sd_esq_w: "",
        cereb_ir_esq_w: "",
        cereb_ip_esq_w: "",
        cereb_sd_esq_w: "",
        utder_ir_esq_w: "",
        utder_ip_esq_w: "",
        utder_sd_esq_w: "",
        utizq_ir_esq_w: "",
        utizq_ip_esq_w: "",
        utizq_sd_esq_w: "",
        observ_flujomet_esq_w: "",
        anatom_fetal_esq_w: "",
        anatom_anormal_esq_w: "",
        lactancia_esq_w: "",
      },

      riesgo_biopsicosocial_esq_w: {
        infertilidad_aborto_esq_w: "",
        retencion_pacentaria_esq_w: "",
        hta_inducida_embar_esq_w: "",
        mortinato_muerte_neo_esq_w: "",
        tp_dificil_esq_w: "",
        qx_gineco_ectopico_esq_w: "",
        enf_renal_cronica_esq_w: "",
        diab_gestacional_esq_w: "",
        diab_mellitus_esq_w: "",
        enf_cardiaca_esq_esq_w: "",
        enf_infec_agudas_esq_w: "",
        enf_autoinmunes_esq_w: "",
        anemia_hb_esq_w: "",
        hemorragia_men_20_esq_w: "",
        hemorragia_may_20_esq_w: "",
        emb_prolongado_esq_w: "",
        hta_esq_w: "",
        rpm_esq_w: "",
        rciu_esq_w: "",
        emb_multiple_esq_w: "",
        mala_presenta_esq_w: "",
        isoinm_rh_esq_w: "",
        tension_emocional_esq_w: "",
        humor_depresivo_esq_w: "",
        sinto_neurovegeta_esq_w: "",
        soporte_fami_tiempo_esq_w: "",
        soporte_fami_espacio_esq_w: "",
        soporte_fami_dienro_esq_w: "",
      },

      prenatal_esq_w: {
        fecha_aseso_pre_esq_w: "",
        fecha_aseso_pos_esq_w: "",
        fecha_eco_obst_esq_w: "",
        fecha_vac_influ_esq_w: "",
        fecha_vac_tdap_esq_w: "",
        fecha_vac_tt_esq_w: "",
      },

      fecha_interconsulta_esq_w: {
        fecha_gineco_esq_w: "",
        fecha_odonto_esq_w: "",
        fecha_nutri_esq_w: "",
        fecha_psicol_esq_w: "",
      },

      hepatitis_b_esq_w: {
        fecha_hepat_b_esq_w: "",
        resultado_hepat_b_esq_w: "",
        nro_dosis_tt_esq_w: "",
      },

      prenatal2_esq_w: {
        fecha_eco_morfo_esq_w: "",
        fecha_eco_percen_esq_w: "",
        fecha_vac_dpt_esq_w: "",
      },

      tabla_vih_esq_w: [
        { fecha_vih_esq_w: "", resultado_vih_esq_w: "" },
        { fecha_vih_esq_w: "", resultado_vih_esq_w: "" },
        { fecha_vih_esq_w: "", resultado_vih_esq_w: "" },
      ],

      tabla_serolo_esq_w: [
        { fecha_serolo_esq_w: "", resultado_serolo_esq_w: "" },
        { fecha_serolo_esq_w: "", resultado_serolo_esq_w: "" },
        { fecha_serolo_esq_w: "", resultado_serolo_esq_w: "" },
      ],

      tabla_hemogl_esq_w: [
        { fecha_hemogl_esq_w: "", resultado_hemogl_esq_w: "" },
        { fecha_hemogl_esq_w: "", resultado_hemogl_esq_w: "" },
        { fecha_hemogl_esq_w: "", resultado_hemogl_esq_w: "" },
      ],

      tabla_igg_esq_w: [
        { fecha_igg_esq_w: "", resultado_igg_esq_w: "" },
        { fecha_igg_esq_w: "", resultado_igg_esq_w: "" },
        { fecha_igg_esq_w: "", resultado_igg_esq_w: "" },
      ],

      tabla_glicem_esq_w: [
        { fecha_glicem_esq_w: "", resultado_glicem_esq_w: "" },
        { fecha_glicem_esq_w: "", resultado_glicem_esq_w: "" },
        { fecha_glicem_esq_w: "", resultado_glicem_esq_w: "" },
      ],

      tabla_hemogra_esq_w: [
        { fecha_hemogra_esq_w: "", resultado_hemogra_esq_w: "" },
        { fecha_hemogra_esq_w: "", resultado_hemogra_esq_w: "" },
        { fecha_hemogra_esq_w: "", resultado_hemogra_esq_w: "" },
      ],

      tabla_hemopara_esq_w: [
        { fecha_hemopara_esq_w: "", resultado_hemopara_esq_w: "" },
        { fecha_hemopara_esq_w: "", resultado_hemopara_esq_w: "" },
        { fecha_hemopara_esq_w: "", resultado_hemopara_esq_w: "" },
      ],

      tabla_fta_abs_esq_w: [
        { fecha_fta_abs_esq_w: "", resultado_fta_abs_esq_w: "" },
        { fecha_fta_abs_esq_w: "", resultado_fta_abs_esq_w: "" },
        { fecha_fta_abs_esq_w: "", resultado_fta_abs_esq_w: "" },
      ],

      tabla_uroanali_esq_w: [
        { fecha_uroanali_esq_w: "", resultado_uroanali_esq_w: "" },
        { fecha_uroanali_esq_w: "", resultado_uroanali_esq_w: "" },
        { fecha_uroanali_esq_w: "", resultado_uroanali_esq_w: "" },
      ],

      tabla_uroculti_esq_w: [
        { fecha_uroculti_esq_w: "", resultado_uroculti_esq_w: "" },
        { fecha_uroculti_esq_w: "", resultado_uroculti_esq_w: "" },
        { fecha_uroculti_esq_w: "", resultado_uroculti_esq_w: "" },
      ],

      tabla_frotisv_esq_w: [
        { fecha_frotisv_esq_w: "", resultado_frotisv_esq_w: "" },
        { fecha_frotisv_esq_w: "", resultado_frotisv_esq_w: "" },
        { fecha_frotisv_esq_w: "", resultado_frotisv_esq_w: "" },
      ],

      tabla_glicemia_esq_w: [
        { fecha_glicemia_esq_w: "", resultado_glicemia_esq_w: "" },
        { fecha_glicemia_esq_w: "", resultado_glicemia_esq_w: "" },
        { fecha_glicemia_esq_w: "", resultado_glicemia_esq_w: "" },
      ],

      tabla_vdrl_esq_w: [
        { fecha_vdrl_esq_w: "", resultado_vdrl_esq_w: "" },
        { fecha_vdrl_esq_w: "", resultado_vdrl_esq_w: "" },
        { fecha_vdrl_esq_w: "", resultado_vdrl_esq_w: "" },
      ],

      tabla_glucosa_esq_w: [
        { fecha_glucosa_esq_w: "", resultado_glucosa_esq_w: "" },
        { fecha_glucosa_esq_w: "", resultado_glucosa_esq_w: "" },
        { fecha_glucosa_esq_w: "", resultado_glucosa_esq_w: "" },
      ],

      tabla_ptog_esq_w: [
        { fecha_ptog_esq_w: "", resultado_ptog_esq_w: "" },
        { fecha_ptog_esq_w: "", resultado_ptog_esq_w: "" },
        { fecha_ptog_esq_w: "", resultado_ptog_esq_w: "" },
      ],

      tabla_gota_grues_esq_w: [
        { fecha_gota_grues_esq_w: "", resultado_gota_grues_esq_w: "" },
        { fecha_gota_grues_esq_w: "", resultado_gota_grues_esq_w: "" },
        { fecha_gota_grues_esq_w: "", resultado_gota_grues_esq_w: "" },
      ],

      tabla_estrep_b_esq_w: [
        { fecha_estrep_b_esq_w: "", resultado_estrep_b_esq_w: "" },
        { fecha_estrep_b_esq_w: "", resultado_estrep_b_esq_w: "" },
        { fecha_estrep_b_esq_w: "", resultado_estrep_b_esq_w: "" },
      ],

      tabla_igm_esq_w: [
        { fecha_igm_esq_w: "", resultado_igm_esq_w: "" },
        { fecha_igm_esq_w: "", resultado_igm_esq_w: "" },
        { fecha_igm_esq_w: "", resultado_igm_esq_w: "" },
      ],

      tabla_rubeo_igg_esq_w: [
        { fecha_rubeo_igg_esq_w: "", resultado_rubeo_igg_esq_w: "" },
        { fecha_rubeo_igg_esq_w: "", resultado_rubeo_igg_esq_w: "" },
        { fecha_rubeo_igg_esq_w: "", resultado_rubeo_igg_esq_w: "" },
      ],

      tabla_rubeo_igm_esq_w: [
        { fecha_rubeo_igm_esq_w: "", resultado_rubeo_igm_esq_w: "" },
        { fecha_rubeo_igm_esq_w: "", resultado_rubeo_igm_esq_w: "" },
        { fecha_rubeo_igm_esq_w: "", resultado_rubeo_igm_esq_w: "" },
      ],

      tabla_chagas_tot_esq_w: [
        { fecha_chagas_tot_esq_w: "", resultado_chagas_tot_esq_w: "" },
        { fecha_chagas_tot_esq_w: "", resultado_chagas_tot_esq_w: "" },
        { fecha_chagas_tot_esq_w: "", resultado_chagas_tot_esq_w: "" },
      ],

      tabla_chagas_sint_esq_w: [
        { fecha_chagas_sint_esq_w: "", resultado_chagas_sint_esq_w: "" },
        { fecha_chagas_sint_esq_w: "", resultado_chagas_sint_esq_w: "" },
        { fecha_chagas_sint_esq_w: "", resultado_chagas_sint_esq_w: "" },
      ],

      tabla_tsh_esq_w: [
        { fecha_tsh_esq_w: "", resultado_tsh_esq_w: "" },
        { fecha_tsh_esq_w: "", resultado_tsh_esq_w: "" },
        { fecha_tsh_esq_w: "", resultado_tsh_esq_w: "" },
      ],

      tabla_citolo_cerv_esq_w: [
        { fecha_citolo_cerv_esq_w: "", resultado_citolo_cerv_esq_w: "" },
        { fecha_citolo_cerv_esq_w: "", resultado_citolo_cerv_esq_w: "" },
        { fecha_citolo_cerv_esq_w: "", resultado_citolo_cerv_esq_w: "" },
      ],
    };
  },

  WS_8001: () => {
    return {
      tipo: 0,

      dato_fam: {
        hiper_fam: "",
        paren_hiper_fam: "",
        diabet_fam: "",
        paren_diabet_fam: "",
        cardiopat_fam: "",
        paren_cardiopat_fam: "",
        can_cuell_fam: "",
        paren_can_cuell_fam: "",
        can_mama_fam: "",
        paren_can_mama_fam: "",
        otro_can_fam: "",
        paren_otro_can_fam: "",
      },

      dato_per: {
        hiper_per: "",
        viol_gen_per: "",
        diabet_per: "",
        sangrado_vag_per: "",
        tumores_per: "",
        cirug_pel_per: "",
        infec_pelvi_per: "",
        crioterapia_per: "",
        infec_cervi_per: "",
        radioterapia_per: "",
        flujo_vag_per: "",
        histerectomia_per: "",
        can_cuell_per: "",
        conizacion_per: "",
        can_mama_per: "",
        exeresis_per: "",
        fuma_per: "",
        otros_antec_per: "",
      },

      dato_gineco: {
        inicio_rel_sex: 0,
        planifica: "",
        posparto: "",
        menopausia: "",
      },

      dato_soc_cul: {
        reci_apoy_social: "",
        cual_apoy_social: "",
        vivienda_propia: "",
        vivienda_hacina: "",
        casa: "",
        apto: "",
        invasion: "",
        lote: "",
        estudia_act: "",
        trabaja_act: "",
        que_trabajo: "",
        actividad_fisica: "",
        actividad_recrea: "",
        alimentacion_adec: "",
        cuantas_x_dia: "",
        cuantas_con_famil: "",
        sueno_normal: "",
        horas_sueno: "",
        tabaco: "",
        alcohol: "",
        otras_sustacias: "",
        cual_sustacias: "",
      },

      especuloscopia: {
        aspecto_cuell: "",
        otro_aspecto: "",
      },

      recepcion_entrega: {
        ips_lect: "",
        ano_entre: "",
        mes_entre: "",
        dia_entre: "",
        resultado: "",
        aten_medico: "",
        educacion: "",
        seguimiento: "",
        descripcion: "",
        ano_consul: "",
        mes_consul: "",
        dia_consul: "",
      },

      control: {
        ano_toma: "",
        mes_toma: "",
        dia_toma: "",
        conduc_manejo: "",
        aspect_geni: "",
        flujo_car: "",
        educa_prev: "",
        remision_cod: "",
        ano_cuando: "",
        mes_cuando: "",
        dia_cuando: "",
        observ_contr: "",
      },
    };
  },
  WS_8002: () => {
    return {
      tipo_paci: "",
      gestaciones: "",
      fecha_regla: "",
      partos: "",
      abortos: "",
      cesareas: "",
      nacidos_muertos: "",
      nacidos_vivos: "",
      ets: "",
      fecha_ult_cito: "",
      institucion_ult_cito: "",
      resultado_ult_cito: "",
      proced_cuello: "",
      fecha_proced_cuello: "",
      aspecto_cuello: "",
      observaciones_cit: "",
      primer_cito: "",
      vacunas_vph: "",
      ets_cual: "",
      dispareunia: "",
      fecha_prox_cito: "",
    };
  },
  WS_8031: () => {
    return {
      tipo: 0,

      dato_fam: {
        hiper_fam: "",
        paren_hiper_fam: "",
        diabet_fam: "",
        paren_diabet_fam: "",
        cardio_vas_fam: "",
        paren_cardio_vas_fam: "",
        can_cuell_fam: "",
        paren_can_cuell_fam: "",
        can_mama_fam: "",
        paren_can_mama_fam: "",
        otro_can_fam: "",
        paren_otro_can_fam: "",
        enf_mental_fam: "",
        paren_enf_mental_fam: "",
        gine_obst_fam: "",
        paren_gine_obst_fam: "",
        viol_gen_fam: "",
        paren_viol_gen_fam: "",
        otros_antec_fam: "",
      },

      dato_per: {
        hiper_per: "",
        diabet_per: "",
        cardio_vas_per: "",
        trombofle_per: "",
        its_per: "",
        viol_gen_per: "",
        alergias_per: "",
        cefaleas_per: "",
        migra_aura_per: "",
        enf_mental_per: "",
        gine_obst_per: "",
        hepatopatias_per: "",
        cirug_per: "",
        cual_cirug_per: "",
        can_mama_per: "",
        can_cuell_per: "",
        otro_can_per: "",
        hemorrag_vag_per: "",
        otros_antec_per: "",
      },

      dato_soc_cul: {
        reci_apoy_social: "",
        cual_apoy_social: "",
        vivienda_propia: "",
        vivienda_hacina: "",
        casa: "",
        apto: "",
        invasion: "",
        lote: "",
        estudia_act: "",
        trabaja_act: "",
        actividad_fisica: "",
        actividad_recrea: "",
        alimentacion_adec: "",
        cuantas_x_dia: "",
        cuantas_con_famil: "",
        sueno_normal: "",
        horas_sueno: "",
        cigarrillo: "",
        cuantos_cigarr: "",
        alcohol: "",
        abuso: "",
        otras_sustancias: "",
        cual_sustancias: "",
      },

      signos_vitales: {
        aspecto_gen: "",
        mamas: "",
        piel_fan_muc: "",
        cabeza: "",
        agudeza_vis: "",
        genitales_ext: "",
        salud_bucal: "",
        cuello_tiroi: "",
        torax: "",
        cardio_pulmo: "",
        abdomen: "",
        genito_urina: "",
        columna: "",
        extremidad_inf: "",
        neurologico: "",
        dolor_palpacion: "",
        sangrado_contac: "",
      },

      asesoria_eleccion: {
        metodo_eleg: "",
        examen_prac: "",
        cual_examen_prac: "",
        efecto_secun: "",
        uso_correc_met: "",
        impor_controles: "",
        alarma_metodo: "",
        deman_citol: "",
        instructivo_recom: "",
        prevencion: "",
        mecanismo_accion: "",
        autocuidado: "",
        autoexamen_mama: "",
        otro_tema: "",
        cual_tema: "",
      },

      control: {
        metodo_ant: "",
        tiempo_uso: "",
        satisfaccion: "",
        vision_borr: "",
        dolor_abdomen: "",
        dolor_torax: "",
        dolor_brazo: "",
        mareo: "",
        manchas_piel: "",
        edema_pies: "",
        varices: "",
        dolor_pelvico: "",
        flujo_vag: "",
        dolor_cabeza: "",
        dolor_piernas: "",
        sangrado_vag: "",
        cambios_comporta: "",
        molestia_palmas: "",
        sintoma_ord: "",
        exp_subdermico: "",
        exp_intrauterino: "",
        continua_metodo: "",
        nuevo_metodo: "",
        fecha_cambio: "",
        remitido: "",
        fecha_proxima: "",
      },

      dato_fam2: {
        cual_hiper: "",
        cual_diabet: "",
        cual_cardipo: "",
        cual_cuello: "",
        cual_mama: "",
        cual_otro_can: "",
        cual_enf_mental: "",
        cual_gineco_obs: "",
        cual_violencia: "",
      },

      dato_per2: {
        embarazo_ectopico: "",
      },

      dato_fam3: {
        cual_its_per: "",
      },

      brinda_educ_1: "",

      brinda_educ_2: "",

      brinda_educ_3: "",
    };
  },
  WS_8051: () => {
    //WS8051
    return {
      ant_personales: {
        perinatales: "",
        crecimiento: "",
        desarrollo: "",
        vacunas: "",
        enf_cronica: "",
        discapacidad: "",
        enf_infe_cont: "",
        accidentes: "",
        accid_frec: "",
        uso_medictam: "",
        problem_psico: "",
        violencia: "",
        judiciales: "",
        observ_pers: "",
      },
      ant_familiares: {
        diabetes: "",
        dia_quien: "",
        obesidad: "",
        obe_quien: "",
        cardiovascular: "",
        car_quien: "",
        alergia: "",
        ale_quien: "",
        infecciones: "",
        inf_quien: "",
        cancer: "",
        can_quien: "",
        fam_psico: "",
        fam_quien: "",
        alcohol_drog: "",
        alc_quien: "",
        violencia_fam: "",
        vio_quien: "",
        madre_padre_adol: "",
        mad_quien: "",
        fam_judiciales: "",
        fam_jud_quien: "",
        otros: "",
        neurologicos: "",
        neu_quien: "",
        observ_fam: "",
      },
      familia: {
        vive_lugar: "",
        convive_madre: "",
        convive_padre: "",
        convive_madrastra: "",
        convive_padrastro: "",
        convive_hermanos: "",
        convive_pareja: "",
        convive_hijo: "",
        convive_otros: "",
        fam_nivel_estud: {
          niv_estud_padre: "",
          semestre_estud_padre: "",
          niv_estud_madre: "",
          semestre_estud_madre: "",
          niv_estud_pareja: "",
          semestre_estud_pareja: "",
        },
        fam_trabajo: {
          ocup_padre: "",
          ocup_estable_padre: "",
          ocup_madre: "",
          ocup_estable_madre: "",
          ocup_pareja: "",
          ocup_estable_pareja: "",
        },
        apoyo_social_subsidio: "",
        percepcion_familia: "",
        observacion_familia: "",
      },
      vivienda: {
        electricidad: "",
        acueducto: "",
        alcantarillado: "",
        hacinamiento: "",
        gas_domicilia: "",
        internet: "",
        observacion_vivienda: "",
      },
      educacion: {
        estudia: "",
        institucion_est: "",
        nivel_estud: "",
        grado_curso: "",
        anos_aprobados: "",
        problemas_escuela: "",
        anos_repetidos: "",
        causa_repetidos: "",
        violencia_escolar: "",
        desercion_exclusion: "",
        causa_desercion: "",
        educacion_no_formal: "",
        cual_edu_no_formal: "",
        observacion_educacion: "",
      },
      trabajo: {
        actividad: "",
        edad_inicio_trabajo: "",
        horas_semanales: "",
        horario_trabajo: "",
        razon_trabajo: "",
        trabajo_legalizado: "",
        trabajo_insalubre: "",
        tipo_trabajo: "",
        observ_trabajo: "",
      },
      vida_social: {
        aceptacion: "",
        tiene_pareja: "",
        edad_pareja: "",
        violencia_pareja: "",
        amigos: "",
        horas_act_fisica: "",
        horas_tv_dia: "",
        horas_pc_dia: "",
        horas_videojuegos_dia: "",
        otras_actividades: "",
        observaciones_social: "",
      },
      habitos_consumo: {
        sueno_normal: "",
        sueno_horas: "",
        alimenta_adecuada: "",
        comidas_dia: "",
        comidas_familia: "",
        tabaco: "",
        tabaco_edad_inicio: "",
        nro_ciga_dia: "",
        alcohol: "",
        alcohol_edad_inicio: "",
        alcohol_abuso: "",
        otras_sustancias: "",
        edad_inicio_sust: "",
        repercucion_sust: "",
        conduce_vehiculo: "",
        cual_vehiculo: "",
        seguridad_val: "",
        observ_hab_cons: "",
      },
      gineco_urologico: {
        menar_espermar: "",
        fecha_ult_mens: "",
        ciclos_regulares: "",
        dismenorrea: "",
        flujo_secrecion: "",
        vih: "",
        vih_tratamiento: "",
        vih_busq_contac: "",
        vih_trata_contac: "",
        gine_its: "",
        its_tratamiento: "",
        its_cual: "",
        its_busq_contac: "",
        its_trata_contac: "",
        embarazos: "",
        hijos: "",
        gine_abortos: "",
        edad_1er_embar: "",
        termino_1er_embar: "",
        observaciones_gine_uro: "",
      },
      sexualidad: {
        relaciones_sex: "",
        pareja_sex: "",
        edad_inicio_sex: "",
        inicio_sex_coercion: "",
        dificultad_rel_sex: "",
        consejeria_sex: "",
        uso_correcto_sex: "",
        uso_habitual_condon: "",
        satis_metodo_plan: "",
        eco_emergen_sex: "",
        observaciones_sex: "",
      },
      psico_emocional: {
        imagen_corp: "",
        estado_animo: "",
        proyecto_vida: "",
        redes_social_apoyo: "",
        ref_adulto: "",
        ref_adulto_cel: "",
        ref_adulto_fijo: "",
        observacion_psico: "",
      },
      examen_fisico: {
        piel_faner_mucosa: "",
        cabeza: "",
        agudeza_visual: "",
        agudeza_auditiva: "",
        salud_bucal: "",
        cuello_tiroides: "",
        toras_mamas: "",
        cardio_pulmon: "",
        abdomen: "",
        genito_urin: "",
        columna: "",
        extremidades: "",
        neurologico: "",
      },
      desarrollo_puberal: {
        edad_telarquia: "",
        edad_pubarquia: "",
        edad_vello_axilar: "",
        edad_polucion: "",
        edad_menarquia: "",
        ritmo_mestrual: "",
        cantidad: "",
        coagulos: "",
        dolor_menstrual: "",
        mastodinia: "",
        observaciones_desa_pub: "",
      },
      sexualidad2: {
        pareja_actual_sex2: "",
        tiempo_rela_sex2: "",
        edad_pareja_sex2: "",
        activ_pareja_sex2: "",
        hrs_trabajo_parej_sex2: "",
        estad_civil_parej_sex2: "",
        niv_educ_parej_sex2: "",
        exp_vaginal_sex2: "",
        exp_oral_sex2: "",
        exp_anal_sex2: "",
        exp_otros_sex2: "",
        juguetes_sex2: "",
        frec_coital_sex2: "",
        tipo_frec_coital_sex2: "",
        nro_parejas_sex2: "",
        observaciones_sex2: "",
      },
      abuso_sexual: {
        abuso_sex: "",
        tipo_abuso: "",
        quien_abuso: "",
        denuncia_abuso: "",
        donde_denuncia: "",
        edad_agresor: "",
        cantidad_agresor: "",
        edad_inicio_abuso: "",
        t_anos_abuso: "",
        t_meses_abuso: "",
        t_semanas_abuso: "",
        tratamiento_abuso: "",
        observ_abuso: "",
      },
      frecundidad: {
        abortos: {
          abort_esp: "",
          abort_prov: "",
          abort_emb_eto: "",
        },
        nacimientos: {
          nac_vivos: "",
          nac_muerto: "",
        },
        edad_1er_emb: "",
        patol_embar: "",
        cual_patol_embar: "",
        edad_1er_parto: "",
        hospital: "",
        infeccion: "",
        lactancia_act: "",
        lact_pesada: "",
        max_lact: "",
        min_lact: "",
        regulacion_menst: "",
        peso_1er_rn: "",
        peso_2do_rn: "",
        peso_3ro_rn: "",
        peso_4to_rn: "",
        observacion_frecun: "",
      },
      its: {
        conoce: "",
        cuales_conoce: "",
        tenido_its: "",
        cual_tenido: "",
        trata_its: "",
        cual_trata_its: "",
        pareja_its: "",
        cual_pareja_its: "",
        pareja_tenido_its: "",
        pareja_cual_tenido_its: "",
        trata_pareja_its: "",
        cual_trata_pareja_its: "",
        observacion_its: "",
      },
      examen_fisico2: {
        patron_vello: "",
      },
      genito_urinario: {
        flu_vag_ant: "",
        flu_vag_olor: "",
        flu_color_vag: "",
        flujo_act: "",
        flujo_duracion: "",
        flujo_molestia: "",
        flujo_tratar: "",
        secre_ure_ant: "",
        secre_ure_color: "",
        secre_ure_act: "",
        secre_ure_duracion: "",
        secre_ure_molestia: "",
        secre_ure_tratar: "",
      },
      examen_gineco: {
        mamas_gine: "",
        vello_gine: "",
        vulva_gine: "",
        clitoris_gine: "",
        himen_gine: "",
        vagina_gine: "",
        cuello_uter_gine: "",
        cuerpo_uter_gine: "",
        tacto_vag_gine: "",
        anex_izq_gine: "",
        anex_der_gine: "",
        examen_mama_gine: "",
        toma_muestra_gine: {
          toma_muestra1_gine: "",
          toma_muestra2_gine: "",
        },
        observacion_ex_gineco: "",
      },
      examen_genital_masc: {
        genital_masc: "",
        vello_masc: "",
        pene_cuerpo_masc: "",
        glande_masc: "",
        prepucio_masc: "",
        secrecion_masc: "",
        escroto_masc: "",
        testiculo_der: "",
        testiculo_izq: "",
        examen_mama_masc: "",
        observacion_ex_genital: "",
      },
      examen_comple: {
        hemograma: "",
        sedimento_urin: "",
        quimico_orina: "",
        urocit_antib: "",
        uremia: "",
        glicemia: "",
        nitrogeno_ure: "",
        perfil_lipidi: "",
        vdrl_otro: "",
        ex_vih: "",
        papanicolau: "",
        schiller: "",
        ex_flujo_vag: "",
        cultivo_flu_vag: "",
        perfil_hormonal: "",
        radiografia: "",
        ecografia: "",
        colposcopia: "",
        observacion_ex_comp: "",
      },
      complementa_gineco: {
        citologia: "",
        fecha_cito: "",
      },
    };
  },

  WS_9005: () => {
    return {
      valoracion_9005: "",
      revaloracion_9005: "",
      comer_9005: "",
      lavarse_9005: "",
      vestirse_9005: "",
      arreglarse_9005: "",
      deposicion_9005: "",
      miccion_9005: "",
      bano_9005: "",
      trasladarse_9005: "",
      deambulacion_9005: "",
      escaleras_9005: "",
      nivel_secuelas_9005: "",
      tabla_actividades_9005: "",
      depen_funcional_9005: "",
    };
  },

  WS_9006: () => {
    return {
      valoracion_9006: "",
      revaloracion_9006: "",
      categoria_9006: "",
      actividad_normal_9006: "",
      incapaz_trabajar_9006: "",
      incapaz_cuidarse_9006: "",
    };
  },

  WS_9007: () => {
    return {
      balan_salto_rodilla_9007: "",
      interes_otros_9007: "",
      subir_cosas_9007: "",
      jugar_cucu_escondite_9007: "",
      simula_tel_mune_9007: "",
      senala_pedir_algo_9007: "",
      senala_interes_algo_9007: "",
      juguetes_peque_boca_9007: "",
      acerca_objetos_ensenar_9007: "",
      mira_ojos_segundos_9007: "",
      hipersensible_ruidos_9007: "",
      responde_sonrisa_9007: "",
      imita_9007: "",
      responde_nombre_9007: "",
      mira_juguete_9007: "",
      anda_9007: "",
      mira_cosas_9007: "",
      movim_raros_dedos_cara_9007: "",
      atrae_atencion_propia_9007: "",
      sospecha_sordo_9007: "",
      entiende_gente_9007: "",
      mira_cara_reaccion_des_9007: "",
      mirada_fija_deambula_9007: "",
    };
  },

  WS_9008: () => {
    return {
      edad: "",
      imc: "",
      per_abdo: "",
      activ_fisica: "",
      come_verdu: "",
      medica_hipert: "",
      glucosa_alto: "",
      diabetes_fam: "",
      colesterol_hdl_3m: "",
      valor_colesterol: "",
      valor_hdl: "",
      consume_tabaco: "",
      calc_findrisk: "",
    };
  },

  WS_9009: () => {
    return {
      clasif_heri: "",
      dimension_heri: "",
      profun_tejid: "",
      comorbilidad: "",
      estadio_heri: "",
      infeccion: "",
      tiempo_evolu: "",
      registro_foto: "",
    };
  },

  WS_9010: () => {
    return {
      bajo_peso_nacer: "",
      naci_ant_30sem: "",
      estanc_sup_3odias: "",
      complic_proc_naci: "",
      diag_cond_salud: "",
      riesgo_social: "",
      dific_apren: "",
      prese_orejas: "",
      integ_orejas: "",
      prese_labios: "",
      integ_labios: "",
      prese_lengua: "",
      integ_lengua: "",
      prese_nariz: "",
      integ_nariz: "",
      prese_paladar: "",
      integ_paladar: "",
      prese_ojos: "",
      integ_ojos: "",
      prese_dientes: "",
      integ_dientes: "",
      prese_cuello: "",
      integ_cuello: "",
      prese_hombros: "",
      integ_hombros: "",
      bb_reaccio_ruido: "",
      dif_llanto_bb: "",
      bb_succiona_fuerza: "",
      bb_reac_habla: "",
      bb_gira_cabez_ruido: "",
      bb_repite_sonidos: "",
      bb_rie_con_juegos: "",
      bb_dem_int_canto_hab: "",
      bb_emit_sonido_pedi: "",
      bb_emit_sonido_incom: "",
      nn_dem_aten_hablan: "",
      nn_imit_palab_nuev: "",
      nn_cons_dif_alim: "",
      nn_emit_sonido_pedi: "",
      nn_muest_part_cuerp: "",
      nn_imit_sonido_anim: "",
      nn_toma_obj: "",
      nn_eje_acc_basicas: "",
      nn_pronu_nomb_obj: "",
      nn_pide_obj_palb: "",
      nn_ejec_ordenes: "",
      nn_pron_mas_palab: "",
      nn_acomp_gest_habla: "",
      nn_uti_posesivos: "",
      nn_exp_emoci_musica: "",
      nn_cons_alim_duros: "",
      nn_dem_int_jugar: "",
      nn_resp_preg_hist: "",
      nn_cuest_situ_nuev: "",
      nn_exp_sent_per_cer: "",
      nn_sab_rep_canc: "",
      nn_exp_orac_4palb: "",
      nn_sal_desp: "",
      nn_ejec_acc_consec: "",
      nn_habla_claridad: "",
      nn_exp_opinion: "",
      nn_ident_err_corri: "",
      nn_uti_palb_abst: "",
      nn_exp_arg_acu_desc: "",
      nn_disf_act_fis: "",
      nn_camina_correct: "",
      nn_disf_vuelt_sin_caer: "",
      nn_protege_cae: "",
      nn_disf_juego_extre: "",
      rem_eval: "",
      rem_urgent: "",
    };
  },

  WS_9011: () => {
    return [
      {
        nombre_acomp: "",
        parentesco: "",
        sati_reci_ayuda_fami: "",
        sati_parti_fami_brind: "",
        sati_fami_acept_emp: "",
        sati_fami_exp_afect: "",
        sati_comp_tiemp_fami: "",
      },
      {
        nombre_acomp: "",
        parentesco: "",
        sati_reci_ayuda_fami: "",
        sati_parti_fami_brind: "",
        sati_fami_acept_emp: "",
        sati_fami_exp_afect: "",
        sati_comp_tiemp_fami: "",
      },
      {
        nombre_acomp: "",
        parentesco: "",
        sati_reci_ayuda_fami: "",
        sati_parti_fami_brind: "",
        sati_fami_acept_emp: "",
        sati_fami_exp_afect: "",
        sati_comp_tiemp_fami: "",
      },
      {
        nombre_acomp: "",
        parentesco: "",
        sati_reci_ayuda_fami: "",
        sati_parti_fami_brind: "",
        sati_fami_acept_emp: "",
        sati_fami_exp_afect: "",
        sati_comp_tiemp_fami: "",
      },
      {
        nombre_acomp: "",
        parentesco: "",
        sati_reci_ayuda_fami: "",
        sati_parti_fami_brind: "",
        sati_fami_acept_emp: "",
        sati_fami_exp_afect: "",
        sati_comp_tiemp_fami: "",
      },
    ];
  },

  WS_9012: () => {
    return {
      tipo_vacuna: "",
      nro_dosis: "",
      reaccion_secund: "",
      tipo_reaccion: {
        enrojecimiento_tipo: "",
        prurito_tipo: "",
        erupcion_cuta_tipo: "",
        cefalea_tipo: "",
        fatiga_tipo: "",
        mialgias_tipo: "",
        lipotimia_tipo: "",
        ansiedad_tipo: "",
        rash_cutaneo_tipo: "",
        disnea_tipo: "",
        otros_tipo_reac: "",
      },
      otro_reaccion: "",
      signos: {
        und_peso: "",
        peso: "",
        talla: "",
        imc_corp: "",
        sup_corp: "",
        temp: "",
        fcard: "",
        fresp: "",
        tens1: "",
        tens2: "",
        tens_media: "",
        oximetria: "",
        pvc: "",
        aper_ocul: "",
        resp_verb: "",
        resp_moto: "",
        vlr_glasg: "",
        per_abdo: "",
      },
      observacion_vacuna: "",
      datos_tabla_recom: "",
      etapa_vacuna: "",
      comorbilidad_vacuna: "",
      comorbilidad_confirmada: {
        diabetes: "",
        enf_cardiovas: "",
        falla_renal: "",
        vih: "",
        cancer: "",
        enf_autoinmun: "",
        hipotiroid: "",
        cortico_inmuno: "",
        epoc_asma: "",
        mal_nutricion: "",
        fumadores: "",
      },
      vacunado_covid19: "",
      fecha_vacunacion: "",
    };
  },

  WS_9013: () => {
    return {
      orientacion: {
        ano_mnse: "",
        mes_mnse: "",
        dia_mnse: "",
        dia_semana_mnse: "",
        hora_mnse: "",
        pais_mnse: "",
        ciudad_mnse: "",
        departamento_mnse: "",
        lugar_mnse: "",
        barrio_mnse: "",
      },
      memoria: {
        inten_memoria_mnse: "",
        memoria_mnse: "",
      },
      atencion_calculo: {
        calculo_mnse: "",
      },
      evocacion: {
        evocacion_mnse: "",
      },
      lenguaje: {
        lenguaje1_mnse: "",
        lenguaje2_mnse: "",
        lenguaje3_mnse: "",
        lenguaje4_mnse: "",
        lenguaje5_mnse: "",
        lenguaje6_mnse: "",
      },
      alteracion_visual: {
        tiene_alt_visual: "",
        puntua_alt_visual: "",
      },
      edad: {
        mayor_65: "",
        mayor_75: "",
      },
    };
  },

  WS_9014: () => {
    return {
      tos: "",
      flema_mocos: "",
      sin_aire: "",
      mayor_40: "",
      fuma_exfuma: "",
      calc_epoc: "",
    };
  },

  WS_9016: () => {
    return {
      jornada: "",
      fecha_accid: {
        ano_accid: "",
        mes_accid: "",
        dia_accid: "",
      },
      hora_accid: {
        hr_accid: "",
        mn_accid: "",
        am_pm_accid: "",
      },
      labor_habitual: "",
      tipo_accid: "",
      sitio_accid: "",
      part_cuerpo_afect: "",
    };
  },

  WS_9501: () => {
    return {
      // WS 9501
      signo_peligro: {
        peligr: "",
        tpecho: "",
        letarg: "",
        vomito: "",
        convul: "",
        enfpal: "",
        enfmal: "",
        enfmue: "",
        enfapn: "",
        enffie: "",
        enfale: "",
        enfcia: "",
        enfque: "",
        enfpau: "",
        enfvih: "",
        enftaq: "",
        enfbra: "",
        enfmfo: "",
        enflle: "",
        enfict: "",
        enfpet: "",
        enfequ: "",
        enfhem: "",
        enffon: "",
        enfdis: "",
        enfsec: "",
        enferi: "",
        enfomb: "",
        edepalp: "",
        enfpus: "",
        enfpla: "",
        enf_observ: "",
      },
      signo_tos: {
        tosomnol: "",
        tosbeber: "",
        tosres: "",
        tosdia: "",
        tosgrip: "",
        tosapnea: "",
        tosprem: "",
        tosrap: "",
        tossib: "",
        tostri: "",
        tosest: "",
        tosibi: "",
        tos_observ: "",
      },
      signo_diare: {
        diarre: "",
        diadia: "",
        dialet: "",
        diasan: "",
        diaojo: "",
        bebsed: "",
        pliegu: "",
        dia_alim: "",
        dia_liqu: "",
        diavom_cant: "",
        dia_cant_24h: "",
        dia_cant_4h: "",
      },
      signo_fiebr: {
        fiebre: "",
        fiedia: "",
        fierig: "",
        fieasp: "",
        fiepost: "",
        fiesan: "",
        fiedol: "",
        fietorn: "",
        fiepie: "",
        fiedeng: "",
        fiemalur: "",
        fiemalru: "",
        fieeru: "",
        fiecapi: "",
        fieapari: "",
        fieconvul: "",
        fieciano: "",
        fieneuro: "",
        fiesocial: "",
        fietodia: "",
        fiecef: "",
        fieocu: "",
        fiemial: "",
        fieastr: "",
        fiehepa: "",
        fielipo: "",
        fiepulso: "",
        fieascit: "",
        fiediure: "",
        fiemanif: "",
        fiegota: "",
        fieparc: "",
        fie_tgo: "",
        fietrombo: "",
        fieleucop: "",
        fiehemato: "",
      },
      signo_oido: {
        oidopr: "",
        oiddol: "",
        oidsup: "",
        oiddia: "",
        oidtim: "",
        oidnum: "",
        oidnum_12: "",
        oidtac: "",
      },
      signo_gargan: {
        gargan: "",
        gardol: "",
        garcue: "",
        garexu: "",
        garg_observ: "",
      },
      signo_maltrato: {
        maltra: "",
        malpro: "",
        maline: "",
        malcua: "",
        maldis: "",
        malexp: "",
        malcor: "",
        malalt: "",
        malcrian: "",
        malcon: "",
        malhig: "",
        malt_observ: "",
        malcran: "",
        malquem: "",
        malfract: "",
        malcuta: "",
        maltrame: "",
        malemoci: "",
        malexprob: "",
        malinade: "",
        malautori: "",
        malviolen: "",
        malsalud: "",
        malcalle: "",
        malasiste: "",
      },
      signo_abusex: {
        abusex: "",
        abusex_sang: "",
        abusex_relat: "",
        abusex_vener: "",
        abusex_traum: "",
        abusex_semen: "",
        abusex_activi: "",
        abusex_clamid: "",
        abusex_condil: "",
        abusex_cuerpo: "",
        abusex_comport: "",
        abusex_dolor: "",
        abusex_temor: "",
      },
      signo_salbuc: {
        salbuc_odont: "",
        salbuc_cepil: "",
        salbuc_biber: "",
        salbuc_anteced: "",
        salbuc_trauma: "",
        salbuc_dolor: "",
        salbuc_color: "",
        salbuc_fractu: "",
        salbuc_movil: "",
        salbuc_perdida: "",
        salbuc_lesion: "",
        salbuc_caries: "",
        salbuc_mancha: "",
        salbuc_placa: "",
        salbuc_ulcera: "",
        salbuc_exudado: "",
        salbuc_edema: "",
        salbuc_inflam: "",
        salbuc_enroje: "",
        salbuc_gingiv: "",
        salbuc_abceso: "",
      },
      signo_desnut: {
        despalcon: "",
        desema: "",
        pes_ed_med: "",
        pes_ed_min: "",
        pes_ed_max: "",
        pes_ed_estad: "",
        despal: "",
        talla_ed_med: "",
        talla_ed_min: "",
        talla_ed_max: "",
        talla_ed_estad: "",
        desede: "",
        peso_tal_med: "",
        peso_tal_min: "",
        peso_tal_max: "",
        peso_tal_estad: "",
        per_cef_med: "",
        per_cef_min: "",
        per_cef_max: "",
        per_cef_estad: "",
        destend: "",
        desnobs: "",
      },
      signo_desarr: {
        desarr: "",
        desact: "",
        des_limi_act: "",
        des_test_act: ["", "", "", "", "", "", "", ""],
        des_desact_ant: "",
        des_limi_act_Ant: "",
        des_test_act_ant: ["", "", "", "", "", "", "", ""],
        des_pc_edad: "",
        desobs: "",
        des_prob_embar: "",
        des_prob_parto: "",
        des_prob_salud: "",
        des_prob_paren: "",
        des_prob_disca: "",
        des_prob_entor: "",
        des_prob_desar: "",
      },
      sig_vacunacion: {
        bsghep: "",
        penta1: "",
        penta2: "",
        penta3: "",
        tripl1: "",
        tripl2: "",
        vavop1: "",
        vavop2: "",
        vavop3: "",
        vavop4: "",
        vavop5: "",
        fiebam: "",
        vdptr1: "",
        vdptr2: "",
        neumoc1: "",
        vac_tetanica1: "",
        vac_tetanica2: "",
        vac_bcg: "",
        vac_hepb1: "",
        neumoc2: "",
        neumoc3: "",
        vac_rotavir1: "",
        vac_rotavir2: "",
        vac_varicela: "",
        vac_influenza: "",
        proxvac_dia: "",
        proxvac_mes: "",
        proxvac_ano: "",
      },
      signo_alimentacion: {
        aneleche: "",
        aneveces: "",
        anelecno: "",
        anelecot: "",
        anelecua: "",
        anelevec: "",
        ali_dific: "",
        ali_dejad: "",
        ali_dias: "",
        ali_como: "",
        ali_p_e: "",
        ali_perpeso: "",
        ali_tocaseno: "",
        ali_bocaabi: "",
        ali_lab_inf: "",
        ali_aerola: "",
        ali_agarre: "",
        ali_succion: "",
        volinme: "",
        volcontr: "",
        volsano: "",
        refconsul: "",
        medprev: "",
        recomtrato: "",
        vitaminaA: "",
        prox_vit_A: "",
        albendazol: "",
        hierro: "",
        cuando_hier: "",
        ali_otrleche: "",
        ali_cualleche: "",
        ali_otr_alim: "",
        ali_cualalim: "",
        ali_amamantamiento: "",
        ali_edad: "",
      },
      var_vih: {
        vih_confirm: "",
        vih_sospecha: "",
        vih_posible: "",
        vih_improb: "",
        vih_descart: "",
        sida_est4: "",
        sida_est3: "",
        sida_est2: "",
        sida_est1: "",
      },
      var_neonato: {
        infec_local: "",
        prob_alim_grave: "",
        prob_alim_leve: "",
      },
      enfer_grave: "",
      var_resp: {
        neumo_grave: "",
        neumo_leve: "",
        crup_grave: "",
        crup_leve: "",
        bronquiolitis_grave: "",
        bronquiolitis_leve: "",
        sibilancia_grave: "",
        sibilancia_leve: "",
        resfriado: "",
      },
      var_diarr: {
        diarre_grave: "",
        diarre_deshi: "",
        diarre_riesg: "",
        diarre_leve: "",
        diarre_pers_grave: "",
        diarre_pers_leve: "",
        disenteria: "",
      },
      var_fiebre: {
        febril_grave: "",
        febril_inter: "",
        febril_leve: "",
        malaria_grave: "",
        malaria_leve: "",
        dengue_grave: "",
        dengue_inter: "",
        dengue_proba: "",
      },
      var_oido: {
        mastoid_grave: "",
        otitis_cronic: "",
        otitis_recurr: "",
        otitis_aguda: "",
        otitis_notiene: "",
      },
      var_garganta: {
        faringo_bacte: "",
        faringo_viral: "",
        faringo_notiene: "",
      },
      var_bucal: {
        celulit_faci: "",
        enfer_bucal: "",
        trauma_bucal: "",
        estomatitis: "",
        enfer_denta_gingi: "",
        enfer_bucal_riesg: "",
        enfer_bucal_leve: "",
      },
      var_crecim: {
        obeso: "",
        sobrepeso: "",
        desnutri_grave: "",
        desnutri_leve: "",
        desnutri_riesg: "",
        desnutri_notiene: "",
      },
      var_anemia: {
        anemia_grave: "",
        anemia_leve: "",
        anemia_notiene: "",
      },
      var_maltrato: {
        maltrato_grave: "",
        maltrato_leve: "",
        abuso_sex_grave: "",
        abuso_sex_sospe: "",
        abandono: "",
        maltrato_nohay: "",
      },
      var_epilepsia: {
        prob_neurol_grave: "",
        epilepsia_grave: "",
        epilepsia_gener: "",
        epilepsia_focal: "",
        epilepsia_ausen: "",
        epilepsia_notiene: "",
      },
      var_tubercul: {
        tuberc_grave: "",
        tuberc_confir: "",
        tuberc_clinic: "",
        tuberc_latent: "",
        tuberc_contac: "",
      },
      var_cancer: {
        cancer_posible: "",
        cancer_riesgo: "",
        cancer_probab: "",
      },
      var_diabetes: {
        cetosis_grave: "",
        diabetes_grave: "",
        diabetes_posib: "",
        diabetes_gluco: "",
        diabetes_notiene: "",
      },
      version: "",
      control_desarrollo: {
        edema: "",
        apetito: "",
        inscrito_cyd: "",
        fecha_inscrito_cyd: "",
        nro_controles: "",
        manejo_dnt: "",
        tabla_controles: [
          { fecha_controles: "" },
          { fecha_controles: "" },
          { fecha_controles: "" },
          { fecha_controles: "" },
          { fecha_controles: "" },
        ],
        fecha_pediatria: "",
        fecha_nutricion: "",
        recupera_nutric: "",
        micronutri_pol: "",
      },
      dato_bajo_peso: {
        gemelo: "",
        prematuro: "",
        institu_parto: "",
        hospit_egre: "",
        ano_hospit: "",
        mes_hospit: "",
        dia_hospit: "",
        ano_valoracion: "",
        mes_valoracion: "",
        dia_valoracion: "",
        cita_1er_mes: "",
        ano_cita_1er: "",
        mes_cita_1er: "",
        dia_cita_1er: "",
        edad_cita_1er: "",
        peso_cita_1er: "",
        talla_cita_1er: "",
        ganancia_peso: "",
        gramos_ganados: "",
        tabla_inter: [
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
          { fecha_inter: "", peso_inter: "", talla_inter: "" },
        ],
      },
      nino_6meses: {
        rec_liqui: "",
        rec_leche_for: "",
        rec_leche_otr: "",
        rec_espeso: "",
      },
    };
  },

  WS_9520: () => {
    return {
      tipo_motiv: "",
      nivel_educ: {
        cod_educ: "",
        det_educ: "",
      },
      hijos: {
        nro_hijos: "",
        det_hijos: "",
      },
      recom_postur: "",
      recom_ergon: "",
      aplica: "",
      exam_period: "",
      exam_egreso: "",
      autor_alime: "",
      autor_otros: "",
      autor_porque: "",
      ex_per_reubicado: "",
      ex_per_envia_eps: "",
      ex_per_envia_arp: "",
      ex_per_cont_cargo: "",
      autor_space_confin: "",
      limit: JSON.parse(JSON.stringify(Array(3).fill({ cual: "", func: "", grav: "" }))),
      nit_empre: "",
      version: "",
      ante_labor: {
        activ_empresa: "",
        lab_sede: "",
        lab_empresa: "",
        lab_arp: "",
        lab_pens: "",
        lab_fecha: "",
        lab_jorn: "",
        lab_cargo: "",
        lab_funci: "",
        lab_maqui: "",
        lab_herra: "",
        lab_mater: "",
        lab_riesg: "",
        lab_protec: {
          lab_gafa: "",
          lab_casc: "",
          lab_tapa: "",
          lab_over: "",
          lab_bota: "",
          lab_prot: "",
          lab_resp: "",
          lab_guan: "",
        },
        lab_area_trab: "",
        ant_accid_trab: {
          hay_accid_trab: "",
          fecha_accid_trab: "",
          empresa_accid_trab: "",
          lesion_accid_trab: "",
          parte_accid_trab: "",
          dias_accid_trab: "",
          report_accid_trab: "",
          secuel_accid_trab: "",
          atenc_accid_trab: "",
        },

        hay_enf_prof: "",
        enf1_prof: {
          fecha_enf1_prof: "",
          det_enf1_prof: "",
        },

        enf2_prof: {
          fecha_enf2_prof: "",
          det_enf2_prof: "",
        },

        lab_tab_anter: JSON.parse(
          JSON.stringify(
            Array(4).fill({
              lab_empr_ant: "",
              lab_activ_ant: "",
              lab_secc_ant: "",
              lab_carg_ant: "",
              lab_tiemp_ant: "",
              lab_func_ant: "",
              lab_med_ant: "",
              lab_sop_ant: "",
              lab_cualsop_ant: "",
              lab_emp_act: "",
              // se comenta lab_ries por envio al dll
              lab_ilumi: "",
              lab_radio: "",
              lab_radno: "",
              lab_ruido: "",
              lab_tmalt: "",
              lab_tmbaj: "",
              lab_vibra: "",
              lab_presi: "",
              lab_gases: "",
              lab_humos: "",
              lab_polvo: "",
              lab_liqui: "",
              lab_vapor: "",
              lab_fibra: "",
              lab_cardi: "",
              lab_cares: "",
              lab_disen: "",
              lab_manej: "",
              lab_movim: "",
              lab_video: "",
              lab_micro: "",
              lab_anima: "",
              lab_veget: "",
              lab_conte: "",
              lab_organ: "",
              lab_relac: "",
              lab_gesti: "",
              lab_fisic: "",
              lab_elect: "",
              lab_incen: "",
              lab_explo: "",
              lab_mecan: "",
              lab_locat: "",
              lab_despl: "",
              lab_ordpu: "",
              lab_natur: "",
            })
          )
        ),
      },

      vacun_ant: {
        vac_tetan_dosis: "",
        vac_tetan_ano: "",
        vac_tetan_mes: "",

        vac_famar_dosis: "",
        vac_famar_ano: "",
        vac_famar_mes: "",

        vac_hepaa_dosis: "",
        vac_hepaa_ano: "",
        vac_hepaa_mes: "",

        vac_hepab_dosis: "",
        vac_hepab_ano: "",
        vac_hepab_mes: "",

        vac_influ_dosis: "",
        vac_influ_ano: "",
        vac_influ_mes: "",

        vac_otra1_dosis: "",
        vac_otra1_ano: "",
        vac_otra1_mes: "",

        vac_otra2_dosis: "",
        vac_otra2_ano: "",
        vac_otra2_mes: "",
      },

      hab_ant: {
        alcoh_ant: "",
        frec_alcoh_ant: "",
        anos_alcoh_ant: "",
        tabac_ant: "",
        frec_tabac_ant: "",
        anos_tabac_ant: "",
        psico_ant: "",
        frec_psico_ant: "",
        anos_psico_ant: "",
        cant_alcoh_ant: "",
        cant_tabac_ant: "",
      },

      examenes_ingreso: {
        optometria_ing: "",
        audiometria_ing: "",
        espirometria_ing: "",
        anex_osteo_ing: "",
        anex_cardio_ing: "",
        anex_altu_ing: "",
        laboratorios_ing: "",
        cuadro_hematico: "",
        glicemia: "",
        parcial_orina: "",
        perfil_lipidico: "",
        alcohol_saliva: "",
        marihuana_orina: "",
        cocaina_orina: "",
        creatinina: "",
        psicologia_ing: "",
        manipu_alimen_ing: "",
        koh: "",
        coprologico: "",
        serologia: "",
        frotis_garganta: "",
        resultados_ext: "",
      },

      habitos: {
        deporte: "",
        hr_deporte: "",
        dep_choque: "",
        hr_dep_choque: "",
        act_manual: "",
        hr_act_manual: "",
        of_domes: "",
        hr_of_domes: "",
      },

      recomend: {
        uso_epp: {
          uso_bota_acero: "",
          uso_zapato_goma: "",
          uso_camisa_manga_larga: "",
          uso_casco_cofia: "",
          uso_protec_audi: "",
          uso_protec_sol: "",
          uso_gafas_protec: "",
          uso_protec_resp: "",
        },
        estilo_vida: {
          dieta_grasa_azucar: "",
          menos_alcohol: "",
          medias_antivarices: "",
          control_ta: "",
          control_periodico: "",
          dieta_azucar: "",
        },
        capacitacion: {
          altura_confinado: "",
          induc_sitio_trabaj: "",
          pausas_cada_2_horas: "",
          carga_5_10_15_20_kl: "",
          ss_rx_torax: "",
          ss_rx_cls: "",
          emg_vmc_mm_ss: "",
        },
      },
      paraclin: {
        exa_hemo: "",
        otros_1: "",
        otros_2: "",
        otros_3: "",
        visiom: "",
        visiom_patol: "",
        optome: "",
        espirom: "",
        observ_parac: "",
      },
      anexos: {
        anex_derma: "",
        anex_osteo: "",
        anex_cardio: "",
        anex_alimen: "",
        anex_altura: "",
      },

      otros: "",
      salida: {
        enfermedad_comun: "",
        estudio_ep: "",
        estudio_atep: "",
      },

      variables_comunes: {
        cigarrilo_espi: "",
        frecu_deport_sem_espi: "",
        ingreso_pve: "",
        cual_salida: "",
        estilo_peso: "",
        estilo_fuma: "",
        estilo_fisi: "",
        audiom_od: "",
        audiom_oi: "",
        severi_od: "",
        severi_oi: "",
        cambio_umbral_od: "",
        cambio_umbral_oi: "",
        otitis: "",
        otoscopia: {
          otoscopia_od: "",
          obs_otoscopia_od: "",
          otoscopia_oi: "",
          obs_otoscopia_oi: "",
        },
        autor_altur: "",
        antecedentes_generales: {
          hiper_tens_art: "",
          hipoglicemia: "",
          diabetes: "",
        },
        vision_doble_opto: "",
        observ_parac2: "",
      },

      exam_preingreso: "",
      variables_comunes_2: {
        cual_salida_2: "",
      },

      signos_violencia: "",
      signos_maltrato: "",
      autor_condu: "",
      exa_med_Estudi: {
        inst_educ: "",
        grado: "",
        repitente: "",
        acudiente: "",
        antecedentes_famili: "",
        trata_medico: {
          realiza_trata: "",
          cual_trata: "",
        },
      },

      rehusa_exa_medico: "",
    };
  },
};

async function grabarDetalles(detalles, llaveHC) {
  return new Promise(async (resolve, reject) => {
    for (let key in detalles) {
      // console.log("detalle: ", key);
      if (!(key in dllDetalles)) {
        console.error("Error nombre dll no definido !: " + key);
        reject();
      } else {
        let dll = dllDetalles[key];
        let datos = {
          ...detalles[key],
          datosh: datosEnvio() + llaveHC + `${key}` + "|",
        };

        // console.log(datos);

        await postData(datos, get_url(`APP/HICLIN/${dll}.DLL`))
          .then((data) => {
            // CON851("", `Detalle ${dll} grabada con exito`, null, "success", "Success");
            console.log(`Detalle ${dll} grabado con exito.`, data);
          })
          .catch((err) => {
            console.error(err);
            // CON851("", `Error grabando detalle ${dll}`, null, "error", "Error");
            reject();
          });
      }
    }
    resolve();
  });
}

async function grabarDetallesText(detalle, llaveHC) {
  return new Promise((resolve, reject) => {
    detalle = detalle.enterReplace();
    let lineas_detalle = detalle.strToTable("RENG_DETHC");

    let datos = {
      datosh: datosEnvio() + llaveHC + "|",
      ...lineas_detalle,
    };

    postData(datos, get_url(`APP/HICLIN/SAVE_DETHC.DLL`))
      .then((data) => {
        // CON851("", `Detalle ${dll} grabada con exito`, null, "success", "Success");
        console.log(`Detalle ${llaveHC.slice(23, 27)} grabado con exito.`, data);
        resolve();
      })
      .catch((error) => {
        // CON851("", `Error grabando detalle ${llaveHC.slice(23,27)}`, null, "error", "Error");
        console.log(`Error grabando detalle ${llaveHC.slice(23, 27)}`);
        reject();
      });
  });
}

module.exports = {
  detallesHc,
  grabarDetalles,
  grabarDetallesText,
};
