function CON850_P_MSG(code){
    var msj;
    switch (code){
        case "00":  msj = "Imprimir documento?";
            break;
        case "01":  msj = " Desea grabar datos?";
            break;
        case "02": msj = " Eliminar documento?";
            break;
        case "03": msj = " Salir sin grabar?";
            break;
        case "04": msj = " Continuar el proceso?";
            break;
        case "05": msj = " Proceso total ?";
            break;
        case "06": msj = " Abrir excel?";
            break;
        case "07": msj = " Reprocesar?";
            break;
        case "08": msj = " Codigo NO existe, desea crear?";
            break;
        case "09": msj = " Desea actualizar el cargo?";
            break;
        case "10": msj = " Desea marcar el documento fact?";
            break;
        case "11": msj = "  Imprimir Stiker ?";
            break;
        case "12": msj = " Mostrar Preparaciòn ?";
            break;
        case "13": msj = " Abrir Nuevo Folio   ?";
            break;
        case "14": msj = " Adicionar mas Registros?";
            break;
        case "15": msj = " Factura ya existe, adicionar?" ;
            break;
        case "16": msj = " Liquidar Flete?";
            break;
        case "17": msj = " Enviar directo a la impres.?";
            break;
        case "18": msj = " Desea convertir CRT EN SCL ?";
            break;
        case "19": msj = " Pretende un cambio peligroso ";
            break;
        case "20": msj = " Diligenciar formulario NOPOS?";
            break;
        case "21": msj = " Generar Imagen?";
            break;
        case "22": msj = " Solicitar Autorizacion EPS  ?" ;
            break;
        case "23": msj = " Bloquear impresion?";
            break;
        case "24": msj = " Actualizar corresponsalia?";
            break;
        case "25": msj = "Desea trasladar documento";
            break;
        case "26": msj = "Desea actualizar votante?";
            break;
        case "27": msj = "Desea imprimir recomendaciones";
            break;
        case "28": msj = "Diligenciar procedimien. NOPOS";
            break;
        case "29": msj = "Historia perinatal ?";
            break;
        case "30": msj = "Aplica para exam. laboratorio?";
            break;
        case "31": msj = "Aplica para exam. paraclinicos";
            break;
        case "32": msj = "Ya fue radicada, es un reenvio?";
            break;
        case "33": msj = "Imprimir recomendaciones dengue?";
            break;
        case "34": msj = "Desea Cancelar solicitud?";
            break;
        case "35": msj = "Desea Instalar JAVA?";
            break;
        case "37": msj = "FINALIZAR PARTOGRAMA?";
            break;
        case "38": msj = "REABRIR PARTOGRAMA?";
            break;
        case "39": msj = "Desea crear nueva factura?";
            break;
        case "40": msj = "Desea diligenciar Apache ?";
            break;
        case "41": msj = "Llenar formular. Complementario?";
            break;
        case "42": msj = "Desea formula trimestral?";
            break;
        case "43": msj = "Desea mostrar Bases?";
            break;
        case "44": msj = "Enviar Reporte via Email?";
            break;
        case "45": msj = "Continuar sin cita Medica";
            break;
        case "46": msj = "Enviar Mensaje de texto";
            break;
        case "47": msj = "Ya Escaneo el documento";
            break;
        case "48": msj = "DEMANDA INDUCIDA";
            break;
        case "49": msj = "Cerrar historioas clinicas";
            break;
        case "50": msj = "Desea Reliquidar Comprobantes";
            break;
        case "51": msj = "Asignar Cama";
            break;
        case "52": msj = "Cerrar control de transfusion?";
            break;
        case "53": msj = "Imprimir Anexo tecnico?";
            break;
        case "90": msj = "Licencia proxima a expirar";
            break;
        /*default :  msj = "Error falta actualizar contab";
            break;*/
    }
    msj  = msj ? msj : code;
    return msj;
}
