const { getObjRegHC, } = require("../../HICLIN/scripts/reg_hc");
const { grabarDetalles, detallesHc, } = require("../../HICLIN/scripts/reg_dethc");

const arrays = {
    f8_antecedente: [
        { value: 1, text: "No refiere" },
        { value: 2, text: "No hay datos" },
        { value: 3, text: "No aplica" },
    ],
    resul_citol: [
        { value: "1", text: "Normal" },
        { value: "2", text: "Anormal" },
        { value: "3", text: "No aplica" },
        { value: "4", text: "No sabe" },
    ],

    result_vih: [
        { value: "1", text: "Positivo" },
        { value: "2", text: "Negativo" },
    ],

    result_serolo: [
        { value: "1", text: "Reactivo" },
        { value: "2", text: "No reactivo" },
    ],

    result_hemogra: [
        { value: "1", text: "Normal" },
        { value: "2", text: "Anormal" },
    ],

    soporte_fam: [
        { value: "1", text: "Casi siempre" },
        { value: "2", text: "A veces" },
        { value: "3", text: "Nunca" },
    ],

    resp_Ieca_araii: [
        { value: "1", text: "Si recibe" },
        { value: "2", text: "No fue formulado dentro del plan terapeutico" },
        { value: "3", text: "No recibe, aunque fue formulado dentro del plan" },
        { value: "4", text: "No aplica, paciente con ERC, sin HTA, ni DM" },
    ],
    ciclos_menstruales: [
        { value: '1', text: 'Regulares' },
        { value: '2', text: 'Iregulares' },
    ],
    sabeFechaUltRegla: [
        { value: '1', text: 'Referida por el paciente' },
        { value: '2', text: 'Paciente no sabe (aproximada)' },
    ],
    resp_ocular: [
        { value: 1, text: "Ninguna" },
        { value: 2, text: "Al dolor" },
        { value: 3, text: "A ordenes" },
        { value: 4, text: "Espontanea" },
    ],
    resp_verbal: [
        { value: 1, text: "Ninguna" },
        { value: 2, text: "Incomprensible" },
        { value: 3, text: "Inapropiada" },
        { value: 4, text: "Confusa" },
        { value: 5, text: "Orientada" },
    ],
    resp_moto: [
        { value: 1, text: "Ninguna" },
        { value: 2, text: "Descerebracion" },
        { value: 3, text: "Decorticacion" },
        { value: 4, text: "Retira" },
        { value: 5, text: "Localiza" },
        { value: 6, text: "Obedece orden" },
    ],
    Niv_estudio: [
        { value: '1', text: 'Ninguno' },
        { value: '2', text: 'Pre-escolar' },
        { value: '3', text: 'Primaria.' },
        { value: '4', text: 'Secundaria.' },
        { value: '5', text: 'Bach. basico' },
        { value: '6', text: 'Bach. tecnico' },
        { value: '7', text: 'Normalista' },
        { value: '8', text: 'Tec. profesional' },
        { value: '9', text: 'Tecnologi' },
        { value: 'A', text: 'Profesion' },
        { value: 'B', text: 'Especiali' },
        { value: 'C', text: 'Maestria' },
        { value: 'D', text: 'Doctorado' },
    ],
    resp_Ieca_araii: [
        { value: "1", text: "Si recibe" },
        { value: "2", text: "No fue formulado dentro del plan terapeutico " },
        { value: "3", text: "No recibe, aunque fue formulado dentro del plan" },
        { value: "4", text: "No aplica, paciente con erc sin HTA ni DM" },
    ],
    atiende: [
        { value: '1', text: "Medico especialista" },
        { value: '2', text: "Medico general" },
        { value: '3', text: "Enfermera" },
        { value: '4', text: "Auxiliar enfermeria" },
        { value: '5', text: "Terapeuta y otros" },
        { value: '6', text: "Enfermera jefe PyP" },
        { value: '7', text: "Psicologia" },
        { value: '8', text: "Nutricionista " },
        { value: '9', text: "Sin determinar" },
        { value: 'A', text: "Odontologo" },
        { value: 'H', text: "Higienista oral" },
        { value: 'I', text: "Instrumentacion" },
        { value: 'O', text: "Optometria" },
        { value: 'T', text: "Trabajo social" },
        { value: ' ', text: "Sin determinar" },
    ],
    embarazo: [
        { value: "1", text: "1er trimestre emba" },
        { value: "2", text: "2do trimestre emba" },
        { value: "3", text: "3er trimestre emba" },
        { value: "4", text: "No declara" },
        { value: "9", text: "No aplica" },
    ],
    causa: [
        { value: "1", text: "Accidente de trabajo" },
        { value: "2", text: "Accidente de transito" },
        { value: "3", text: "Accidente rabico" },
        { value: "4", text: "Accidente ofidico" },
        { value: "5", text: "Otro tipo accidente" },
        { value: "6", text: "Evento catastrofico" },
        { value: "7", text: "Lesion por agresion" },
        { value: "8", text: "Lesion autoinfligida" },
        { value: "9", text: "Sospecha maltrato fisico" },
        { value: "10", text: "Sospecha abuso sexual" },
        { value: "11", text: "Sospecha violencia sexual" },
        { value: "12", text: "Sospecha maltrato emocional" },
        { value: "13", text: "Enfermedad general" },
        { value: "14", text: "Enfermedad profesional" },
        { value: "15", text: "No aplica" },
    ],
    tipo_diag: [
        { value: "1", text: "Impresion diagnostica" },
        { value: "2", text: "Confirmado nuevo" },
        { value: "3", text: "Confirmado repetido" },
        { value: "9", text: "No aplica" },
    ],
    finalid: [
        { value: '0', text: "" },
        { value: '1', text: "Atencion parto" },
        { value: '2', text: "Atencion Rec. Nacido" },
        { value: '3', text: "Atencion Planif.Familiar" },
        { value: '4', text: "Det.Alt Crecim <10" },
        { value: '5', text: "Det.Alt.Desa.Joven" },
        { value: '6', text: "Det.Alt.Embarazo  " },
        { value: '7', text: "Det.Alt. Adulto   " },
        { value: '8', text: "Det.Alt.Agud.Visual" },
        { value: '9', text: "Det.Engerm.Profesional." },
        { value: '10', text: "No aplica" },
        { value: '11', text: "Patologia cronica" },
    ],
    estado_sal: [
        { value: 1, text: "Vivo (a)" },
        { value: 2, text: "Muerto (a)" },
        { value: 3, text: "Remitido (a)" },
        { value: 4, text: "Hospitalizado" },
        { value: 5, text: "Observacion" },
    ],
    planific: [
        { value: "1", text: "Diu" },
        { value: "2", text: "Oral" },
        { value: "3", text: "Barrera" },
        { value: "4", text: "Otro" },
        { value: "5", text: "Ninguno" },
        { value: "6", text: "Diu + barrera" },
        { value: "7", text: "Impla. Subdermico" },
        { value: "8", text: "I. Subdermico + barrera" },
        { value: "9", text: "Oral + barrera" },
        { value: "A", text: "Inyectable mensual" },
        { value: "B", text: "Inyectable + barrera" },
        { value: "C", text: "Inyectable trimestral" },
        { value: "D", text: "Trimestral + barrera" },
        { value: "E", text: "Emergencia" },
        { value: "F", text: "Emergencia + barrera" },
        { value: "G", text: "Esterilizacion" },
        { value: "H", text: "Estereliza + barrera" },
        { value: "I", text: "No usa X tradicion" },
        { value: "J", text: "No usa X salud" },
        { value: "K", text: "No usa X negacion" },
        { value: "L", text: "Coitus interruptus" },
        { value: "M", text: "Metodo del ritmo" }
    ],

    orientSexual: [
        { value: '1', text: "Heterosexual" },
        { value: '2', text: "Lesbiana" },
        { value: '3', text: "Bisexual" },
        { value: '4', text: "Gay" },
        { value: '5', text: "Transexual" },
        { value: '6', text: "Intersexual" },
        { value: '7', text: "No aplica" },
    ],

    presentDiscap: [
        { value: '1', text: "Discapacidad fisica" },
        { value: '2', text: "Discapacidad cognitiva" },
        { value: '3', text: "Discapacidad sensorial" },
        { value: '4', text: "Ninguna" },
        { value: '5', text: "Sin dato" },
        { value: '6', text: "Discapacidad auditiva" },
        { value: '7', text: "Discapacidad visual" },
        { value: '8', text: "Discapacidad mental" },
    ],

    condicVulnera: [
        { value: '1', text: "Habitalidad en calle" },
        { value: '2', text: "Trabajo sexual" },
        { value: '3', text: "Adulto mayor de 60 años" },
        { value: '4', text: "Consumo de SPA" },
        { value: '5', text: "Privado de la libertad" },
        { value: '6', text: "Enfermedad mental" },
        { value: '7', text: "Abandono social" },
        { value: '8', text: "Desempleo" },
        { value: '9', text: "Desescolarización" },
        { value: 'A', text: "No aplica" },
    ],
    exisRiesgPsico: [
        { value: '1', text: "Perdida reciente" },
        { value: '2', text: "Conflictos de pareja" },
        { value: '3', text: "Conflicto fliar" },
        { value: '4', text: "Prob. escolares" },
        { value: '5', text: "Stress" },
        { value: '6', text: "Crisis economica" },
        { value: '7', text: "Enfermedad cronica" },
        { value: '8', text: "Victima de matoneo" },
        { value: '9', text: "Antecedente fliar de consumo de spa" },
        { value: 'A', text: "Antecedente fliar de suicidio" },
        { value: 'B', text: "Antecedente de maltrato o violencia" },
        { value: 'C', text: "Falta de compromiso fliar" },
        { value: 'D', text: "Pertenecia a pandillas" },
        { value: 'E', text: "No se identifica" },
        { value: 'F', text: "Ninguno" },
    ],
    accionesRealizad: [
        { value: '1', text: "Notificación a justicia" },
        { value: '2', text: "Notificación a protección" },
        { value: '3', text: "Notificación a edicación" },
        { value: '4', text: "Notificación a desarrollo social" },
        { value: '5', text: "Remisión a salud" },
        { value: '6', text: "Todas" },
        { value: '7', text: "No aplica" },
    ],
    tipoViolencia: [
        { value: '1', text: "Violencia sexual" },
        { value: '2', text: "Violencia intrafamiliar" },
        { value: '3', text: "Violencia fisica" },
        { value: '4', text: "Violencia psicologica" },
        { value: '5', text: "Ataque con acido" },
        { value: '6', text: "Negligencia" },
        { value: '7', text: "Violencia escolar" },
    ],
    dilingTipoViolencia: [
        { value: '1', text: "Acoso y/o violación antes de las 72 horas" },
        { value: '2', text: "Acoso y/o violación despues de las 72 horas" },
        { value: '3', text: "Abuso sexual en menor de 14 años" },
        { value: '4', text: "Ninguna de las anteriores" },
        { value: '5', text: "No aplica" },
    ],

    consejIve: [
        { value: '1', text: "Canaliza para ive" },
        { value: '2', text: "Continua embarazo" },
        { value: '3', text: "Consejeria adopción del bebe" },
        { value: '4', text: "No aplica" },
    ],

    rutaProteccion: [
        { value: '1', text: "ICBF" },
        { value: '2', text: "Comisaria de flia" },
        { value: '3', text: "Inspección de policia" },
        { value: '4', text: "Defensoria" },
        { value: '5', text: "Cabildos indigenas" },
        { value: '6', text: "Resguardo indigena" },
        { value: '7', text: "Violencia escolar" },
        { value: '8', text: "No aplica" },
    ],

    rutaJusticia: [
        { value: '1', text: "Fiscalia" },
        { value: '2', text: "Policia" },
        { value: '3', text: "Juzgado mpal" },
        { value: '4', text: "Cabildo indigena" },
        { value: '5', text: "Reguardo indigena" },
        { value: '6', text: "No aplica" },
    ],
    seguiMenorMaltra: [
        { value: '1', text: "Evaluación a la semana" },
        { value: '2', text: "Visita domiciliaria al mes" },
        { value: '3', text: "Cuatro meses" },
        { value: '4', text: "Al año" },
        { value: '5', text: "Evaluación permanente hasta que este fuera del peligro" },
        { value: '6', text: "Visita domiciliaria a los quince dias" },
        { value: '7', text: "Dos meses" },
        { value: '8', text: "Seis meses" },
        { value: '9', text: "Al año" },
        { value: 'A', text: "Citación periodicas al menor y su familia" },
    ],
    seguiMujerMaltra: [
        { value: '1', text: "Citar a la agredida al mes" },
        { value: '2', text: "Cada 3 meses, durante el primer año" },
        { value: '3', text: "Consulta individual" },
        { value: '4', text: "Visita domiciliaria a los 15 dias" },
        { value: '5', text: "Cada mes durante el primer semestre" },
    ],
    captacionPobl: [
        { value: '1', text: "PYP" },
        { value: '2', text: "Consulta externa" },
        { value: '3', text: "Urgencias" },
        { value: '4', text: "Tamizajes" },
        { value: '5', text: "Otra" },
    ],
    presentac_esq: [
        { value: '1', text: "Cefalico" },
        { value: '2', text: "Podalico" },
        { value: '3', text: "Transverso" },
        { value: '4', text: "No aplica" },
    ],
    situacion_esq: [
        { value: '1', text: "Longitudinal" },
        { value: '2', text: "Transversal" },
        { value: '3', text: "Oblicuo" },
        { value: '4', text: "No aplica" },
    ],
    dorso_obs_esq: [
        [
            { value: '1', text: "Anterior izquierdo" },
            { value: '2', text: "Anterior derecho" },
            { value: '3', text: "Posterior izquierdo" },
            { value: '4', text: "Posterior derecho" },
        ],
        [
            { value: '1', text: "Anterior superior" },
            { value: '2', text: "Anterior inferior" },
            { value: '3', text: "Posterior superior" },
            { value: '4', text: "Posterior inferior" },
        ],
        [
            { value: '1', text: "Polo cef. Sup. Der. Dorso Ant." },
            { value: '2', text: "Polo cef. Sup. Izq. Dorso Ant" },
            { value: '3', text: "Polo cef. Sup. Der. Dorso Pos" },
            { value: '4', text: "Polo cef. Sup. Izq. Dorso Pos" },
            { value: '5', text: "Polo cef. Inf. Der. Dorso Ant." },
            { value: '6', text: "Polo cef. Inf. Izq. Dorso Ant" },
            { value: '7', text: "Polo cef. Inf. Der. Dorso Pos" },
            { value: '8', text: "Polo cef. Inf. Izq. Dorso Pos" },
        ],
    ],
    implantacion_esq: [
        { value: '1', text: "Fundica" },
        { value: '2', text: "Anterior" },
        { value: '3', text: "Posterior" },
        { value: '4', text: "Lateral izquierda" },
        { value: '5', text: "Lateral derecha" },
        { value: '6', text: "Marginal anterior" },
        { value: '7', text: "Marginal posterior" },
        { value: '8', text: "Marginal lateral Izq." },
        { value: '9', text: "Marginal lateral Der." },
        { value: '10', text: "Previa Parcial Lat. Izq." },
        { value: '11', text: "Previa Parcial Lat. Der." },
        { value: '12', text: "Previa Parcial posterior" },
        { value: '13', text: "Previa Parcial anterior" },
        { value: '14', text: "Previa central total" },
        { value: '15', text: "No aplica" },
    ],
    ult_regla_esq_w: [
        { value: '1', text: "Referida por el paciente" },
        { value: '2', text: "Paciente no sabe (Aproximada)" },
    ]

}

const detalle = {};
Object.getOwnPropertyNames(detallesHc).forEach(e => {
    detalle[e] = detallesHc[e]()
})

const modular = {
    ...{
        arrays,
        detalle,
        getObjRegHC: getObjRegHC(),
    },
    grabarDetalles,
}

module.exports = {
    modular
}